// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: calculation.sql

package sqlcgen

import (
	"context"
)

const listCalculationBoundariesBySource = `-- name: ListCalculationBoundariesBySource :many
SELECT calculation_boundary_id, service_id, logical_account_id, usage_limit_source_id,
       boundary_at, boundary_kind, reason, related_id, created_at
FROM calculation_boundaries
WHERE usage_limit_source_id = ?1
ORDER BY boundary_at, calculation_boundary_id
`

func (q *Queries) ListCalculationBoundariesBySource(ctx context.Context, usageLimitSourceID string) ([]CalculationBoundary, error) {
	rows, err := q.db.QueryContext(ctx, listCalculationBoundariesBySource, usageLimitSourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CalculationBoundary{}
	for rows.Next() {
		var i CalculationBoundary
		if err := rows.Scan(
			&i.CalculationBoundaryID,
			&i.ServiceID,
			&i.LogicalAccountID,
			&i.UsageLimitSourceID,
			&i.BoundaryAt,
			&i.BoundaryKind,
			&i.Reason,
			&i.RelatedID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCalculationIntervalsBySource = `-- name: ListCalculationIntervalsBySource :many
SELECT calculation_interval_id, service_id, logical_account_id, usage_limit_source_id,
       limit_definition_id, plan_version_id, cycle_type, valid_from, valid_to,
       state, exclusion_reason, boundary_ids_json, created_at, updated_at
FROM calculation_intervals
WHERE usage_limit_source_id = ?1
ORDER BY valid_from, calculation_interval_id
`

func (q *Queries) ListCalculationIntervalsBySource(ctx context.Context, usageLimitSourceID string) ([]CalculationInterval, error) {
	rows, err := q.db.QueryContext(ctx, listCalculationIntervalsBySource, usageLimitSourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CalculationInterval{}
	for rows.Next() {
		var i CalculationInterval
		if err := rows.Scan(
			&i.CalculationIntervalID,
			&i.ServiceID,
			&i.LogicalAccountID,
			&i.UsageLimitSourceID,
			&i.LimitDefinitionID,
			&i.PlanVersionID,
			&i.CycleType,
			&i.ValidFrom,
			&i.ValidTo,
			&i.State,
			&i.ExclusionReason,
			&i.BoundaryIdsJson,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
