// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: linking.sql

package sqlcgen

import (
	"context"
)

const listUsageCostAssociationsBySource = `-- name: ListUsageCostAssociationsBySource :many
SELECT usage_cost_association_id, usage_cost_source_id, logical_account_id,
       valid_from, valid_to, created_at, updated_at
FROM usage_cost_source_account_links
WHERE usage_cost_source_id = ?1
ORDER BY valid_from, usage_cost_association_id
`

func (q *Queries) ListUsageCostAssociationsBySource(ctx context.Context, usageCostSourceID string) ([]UsageCostSourceAccountLink, error) {
	rows, err := q.db.QueryContext(ctx, listUsageCostAssociationsBySource, usageCostSourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UsageCostSourceAccountLink{}
	for rows.Next() {
		var i UsageCostSourceAccountLink
		if err := rows.Scan(
			&i.UsageCostAssociationID,
			&i.UsageCostSourceID,
			&i.LogicalAccountID,
			&i.ValidFrom,
			&i.ValidTo,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsageCostSourceCompletenessBySource = `-- name: ListUsageCostSourceCompletenessBySource :many
SELECT completeness_id, usage_cost_source_id, valid_from, valid_to, state,
       logical_account_ids_json, excluded_activity_json, created_at, updated_at
FROM usage_cost_source_completeness
WHERE usage_cost_source_id = ?1
ORDER BY valid_from, completeness_id
`

func (q *Queries) ListUsageCostSourceCompletenessBySource(ctx context.Context, usageCostSourceID string) ([]UsageCostSourceCompleteness, error) {
	rows, err := q.db.QueryContext(ctx, listUsageCostSourceCompletenessBySource, usageCostSourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UsageCostSourceCompleteness{}
	for rows.Next() {
		var i UsageCostSourceCompleteness
		if err := rows.Scan(
			&i.CompletenessID,
			&i.UsageCostSourceID,
			&i.ValidFrom,
			&i.ValidTo,
			&i.State,
			&i.LogicalAccountIdsJson,
			&i.ExcludedActivityJson,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsageCostSourcesByHub = `-- name: ListUsageCostSourcesByHub :many
SELECT usage_cost_source_id, hub_id, device_id, raw_service_identifier, created_at
FROM usage_cost_sources
WHERE hub_id = ?1
ORDER BY hub_id, device_id, raw_service_identifier, usage_cost_source_id
`

func (q *Queries) ListUsageCostSourcesByHub(ctx context.Context, hubID string) ([]UsageCostSource, error) {
	rows, err := q.db.QueryContext(ctx, listUsageCostSourcesByHub, hubID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UsageCostSource{}
	for rows.Next() {
		var i UsageCostSource
		if err := rows.Scan(
			&i.UsageCostSourceID,
			&i.HubID,
			&i.DeviceID,
			&i.RawServiceIdentifier,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsageLimitAssociationsBySource = `-- name: ListUsageLimitAssociationsBySource :many
SELECT usage_limit_association_id, usage_limit_source_id, logical_account_id,
       limit_definition_id, valid_from, valid_to, created_at, updated_at
FROM usage_limit_source_links
WHERE usage_limit_source_id = ?1
ORDER BY valid_from, usage_limit_association_id
`

func (q *Queries) ListUsageLimitAssociationsBySource(ctx context.Context, usageLimitSourceID string) ([]UsageLimitSourceLink, error) {
	rows, err := q.db.QueryContext(ctx, listUsageLimitAssociationsBySource, usageLimitSourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UsageLimitSourceLink{}
	for rows.Next() {
		var i UsageLimitSourceLink
		if err := rows.Scan(
			&i.UsageLimitAssociationID,
			&i.UsageLimitSourceID,
			&i.LogicalAccountID,
			&i.LimitDefinitionID,
			&i.ValidFrom,
			&i.ValidTo,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsageLimitSourcesByHub = `-- name: ListUsageLimitSourcesByHub :many
SELECT usage_limit_source_id, hub_id, device_id, account_key, raw_service_identifier,
       window_key, normalized_kind, normalized_metric, normalized_label, created_at
FROM usage_limit_sources
WHERE hub_id = ?1
ORDER BY hub_id, device_id, raw_service_identifier, account_key, window_key, usage_limit_source_id
`

func (q *Queries) ListUsageLimitSourcesByHub(ctx context.Context, hubID string) ([]UsageLimitSource, error) {
	rows, err := q.db.QueryContext(ctx, listUsageLimitSourcesByHub, hubID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UsageLimitSource{}
	for rows.Next() {
		var i UsageLimitSource
		if err := rows.Scan(
			&i.UsageLimitSourceID,
			&i.HubID,
			&i.DeviceID,
			&i.AccountKey,
			&i.RawServiceIdentifier,
			&i.WindowKey,
			&i.NormalizedKind,
			&i.NormalizedMetric,
			&i.NormalizedLabel,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
