// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"database/sql"
)

type DisplaySetting struct {
	Singleton            int64          `json:"singleton"`
	Theme                string         `json:"theme"`
	DisplayTimezone      sql.NullString `json:"display_timezone"`
	TimezoneConfirmed    int64          `json:"timezone_confirmed"`
	WeekStartsOn         int64          `json:"week_starts_on"`
	CompactWindowX       sql.NullInt64  `json:"compact_window_x"`
	CompactWindowY       sql.NullInt64  `json:"compact_window_y"`
	CompactWindowWidth   sql.NullInt64  `json:"compact_window_width"`
	CompactWindowHeight  sql.NullInt64  `json:"compact_window_height"`
	CompactWindowDpi     sql.NullInt64  `json:"compact_window_dpi"`
	CompactWindowMonitor sql.NullString `json:"compact_window_monitor"`
	MainWindowX          sql.NullInt64  `json:"main_window_x"`
	MainWindowY          sql.NullInt64  `json:"main_window_y"`
	MainWindowWidth      sql.NullInt64  `json:"main_window_width"`
	MainWindowHeight     sql.NullInt64  `json:"main_window_height"`
	MainWindowDpi        sql.NullInt64  `json:"main_window_dpi"`
	MainWindowMonitor    sql.NullString `json:"main_window_monitor"`
}

type SchemaMetadatum struct {
	Singleton     int64 `json:"singleton"`
	SchemaVersion int64 `json:"schema_version"`
}
