// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"database/sql"
)

type CollectionAttempt struct {
	AttemptID                string         `json:"attempt_id"`
	HubID                    string         `json:"hub_id"`
	Trigger                  string         `json:"trigger"`
	State                    string         `json:"state"`
	StartedAt                string         `json:"started_at"`
	CompletedAt              sql.NullString `json:"completed_at"`
	AnalyticsIntervalSeconds int64          `json:"analytics_interval_seconds"`
	HealthHttpStatus         sql.NullInt64  `json:"health_http_status"`
	StatsHttpStatus          sql.NullInt64  `json:"stats_http_status"`
	ApiContract              sql.NullString `json:"api_contract"`
	HealthSnapshotID         sql.NullString `json:"health_snapshot_id"`
	StatsSnapshotID          sql.NullString `json:"stats_snapshot_id"`
	FailureCode              sql.NullString `json:"failure_code"`
	FailureDetail            sql.NullString `json:"failure_detail"`
	NormalizationErrorPath   sql.NullString `json:"normalization_error_path"`
}

type ConfigurationAudit struct {
	Sequence   int64          `json:"sequence"`
	AuditID    string         `json:"audit_id"`
	OccurredAt string         `json:"occurred_at"`
	Actor      string         `json:"actor"`
	Action     string         `json:"action"`
	EntityType string         `json:"entity_type"`
	EntityID   string         `json:"entity_id"`
	BeforeJson sql.NullString `json:"before_json"`
	AfterJson  sql.NullString `json:"after_json"`
}

type DisplaySetting struct {
	Singleton            int64          `json:"singleton"`
	Theme                string         `json:"theme"`
	DisplayTimezone      sql.NullString `json:"display_timezone"`
	TimezoneConfirmed    int64          `json:"timezone_confirmed"`
	WeekStartsOn         int64          `json:"week_starts_on"`
	CompactWindowX       sql.NullInt64  `json:"compact_window_x"`
	CompactWindowY       sql.NullInt64  `json:"compact_window_y"`
	CompactWindowWidth   sql.NullInt64  `json:"compact_window_width"`
	CompactWindowHeight  sql.NullInt64  `json:"compact_window_height"`
	CompactWindowDpi     sql.NullInt64  `json:"compact_window_dpi"`
	CompactWindowMonitor sql.NullString `json:"compact_window_monitor"`
	MainWindowX          sql.NullInt64  `json:"main_window_x"`
	MainWindowY          sql.NullInt64  `json:"main_window_y"`
	MainWindowWidth      sql.NullInt64  `json:"main_window_width"`
	MainWindowHeight     sql.NullInt64  `json:"main_window_height"`
	MainWindowDpi        sql.NullInt64  `json:"main_window_dpi"`
	MainWindowMonitor    sql.NullString `json:"main_window_monitor"`
}

type Hub struct {
	HubID                     string         `json:"hub_id"`
	DisplayName               string         `json:"display_name"`
	Url                       string         `json:"url"`
	CollectionEnabled         int64          `json:"collection_enabled"`
	CollectionIntervalSeconds int64          `json:"collection_interval_seconds"`
	ApiContract               sql.NullString `json:"api_contract"`
	CreatedAt                 string         `json:"created_at"`
	UpdatedAt                 string         `json:"updated_at"`
}

type HubAccountCandidate struct {
	HubAccountCandidateID string         `json:"hub_account_candidate_id"`
	HubID                 string         `json:"hub_id"`
	ServiceID             string         `json:"service_id"`
	AccountKey            string         `json:"account_key"`
	DisplayName           string         `json:"display_name"`
	Email                 string         `json:"email"`
	WorkspaceName         string         `json:"workspace_name"`
	DeviceName            string         `json:"device_name"`
	State                 string         `json:"state"`
	LogicalAccountID      sql.NullString `json:"logical_account_id"`
	FirstObservedAt       sql.NullString `json:"first_observed_at"`
	LastObservedAt        sql.NullString `json:"last_observed_at"`
	CreatedAt             string         `json:"created_at"`
	UpdatedAt             string         `json:"updated_at"`
}

type HubConnectionAttempt struct {
	AttemptID     string         `json:"attempt_id"`
	HubID         string         `json:"hub_id"`
	CheckedAt     string         `json:"checked_at"`
	State         string         `json:"state"`
	ApiContract   sql.NullString `json:"api_contract"`
	FailureDetail sql.NullString `json:"failure_detail"`
}

type HubConnectionStatus struct {
	HubID         string         `json:"hub_id"`
	State         string         `json:"state"`
	CheckedAt     sql.NullString `json:"checked_at"`
	FailureDetail sql.NullString `json:"failure_detail"`
}

type IdentificationCandidate struct {
	CandidateID               string         `json:"candidate_id"`
	RawLimitServiceIdentifier string         `json:"raw_limit_service_identifier"`
	RawReportedPlanName       string         `json:"raw_reported_plan_name"`
	State                     string         `json:"state"`
	ServiceID                 sql.NullString `json:"service_id"`
	PlanID                    sql.NullString `json:"plan_id"`
	FirstObservedAt           sql.NullString `json:"first_observed_at"`
	LastObservedAt            sql.NullString `json:"last_observed_at"`
	CreatedAt                 string         `json:"created_at"`
	UpdatedAt                 string         `json:"updated_at"`
}

type IdentificationCandidateObservation struct {
	ObservationID     string `json:"observation_id"`
	CandidateID       string `json:"candidate_id"`
	HubID             string `json:"hub_id"`
	HubAccountDisplay string `json:"hub_account_display"`
	ObservedAt        string `json:"observed_at"`
}

type Judgment struct {
	EntityType string         `json:"entity_type"`
	EntityID   string         `json:"entity_id"`
	State      string         `json:"state"`
	Reason     sql.NullString `json:"reason"`
	UpdatedAt  string         `json:"updated_at"`
}

type LimitDefinition struct {
	LimitDefinitionID   string         `json:"limit_definition_id"`
	ServiceID           string         `json:"service_id"`
	CycleType           string         `json:"cycle_type"`
	Meaning             string         `json:"meaning"`
	Unit                string         `json:"unit"`
	BillingConfirmation string         `json:"billing_confirmation"`
	ArchivedAt          sql.NullString `json:"archived_at"`
	CreatedAt           string         `json:"created_at"`
	UpdatedAt           string         `json:"updated_at"`
}

type LimitLabelChangeCandidate struct {
	CandidateID               string         `json:"candidate_id"`
	HubID                     string         `json:"hub_id"`
	DeviceRecordKey           string         `json:"device_record_key"`
	HubAccountKey             string         `json:"hub_account_key"`
	RawLimitServiceIdentifier string         `json:"raw_limit_service_identifier"`
	NormalizedKind            string         `json:"normalized_kind"`
	NormalizedMetric          string         `json:"normalized_metric"`
	OldLabel                  string         `json:"old_label"`
	NewLabel                  string         `json:"new_label"`
	State                     string         `json:"state"`
	LimitDefinitionID         sql.NullString `json:"limit_definition_id"`
	FirstObservedAt           sql.NullString `json:"first_observed_at"`
	LastObservedAt            sql.NullString `json:"last_observed_at"`
	CreatedAt                 string         `json:"created_at"`
	UpdatedAt                 string         `json:"updated_at"`
}

type LimitLabelChangeWindow struct {
	WindowID    string `json:"window_id"`
	CandidateID string `json:"candidate_id"`
	WindowKey   string `json:"window_key"`
	Label       string `json:"label"`
	ObservedAt  string `json:"observed_at"`
}

type LogicalAccount struct {
	LogicalAccountID string         `json:"logical_account_id"`
	ServiceID        string         `json:"service_id"`
	DisplayName      string         `json:"display_name"`
	ArchivedAt       sql.NullString `json:"archived_at"`
	CreatedAt        string         `json:"created_at"`
	UpdatedAt        string         `json:"updated_at"`
}

type Plan struct {
	PlanID     string         `json:"plan_id"`
	ServiceID  string         `json:"service_id"`
	Name       string         `json:"name"`
	IsBaseline int64          `json:"is_baseline"`
	ArchivedAt sql.NullString `json:"archived_at"`
	CreatedAt  string         `json:"created_at"`
	UpdatedAt  string         `json:"updated_at"`
}

type PlanHistory struct {
	PlanHistoryID    string         `json:"plan_history_id"`
	LogicalAccountID string         `json:"logical_account_id"`
	PlanVersionID    string         `json:"plan_version_id"`
	ValidFrom        string         `json:"valid_from"`
	ValidTo          sql.NullString `json:"valid_to"`
	CreatedAt        string         `json:"created_at"`
	UpdatedAt        string         `json:"updated_at"`
}

type PlanLimitRule struct {
	PlanLimitRuleID   string          `json:"plan_limit_rule_id"`
	PlanVersionID     string          `json:"plan_version_id"`
	LimitDefinitionID string          `json:"limit_definition_id"`
	PlanLimit         sql.NullFloat64 `json:"plan_limit"`
	LimitMultiplier   sql.NullFloat64 `json:"limit_multiplier"`
	OfficialSourceUrl string          `json:"official_source_url"`
	CreatedAt         string          `json:"created_at"`
}

type PlanVersion struct {
	PlanVersionID     string         `json:"plan_version_id"`
	PlanID            string         `json:"plan_id"`
	Name              string         `json:"name"`
	ValidFrom         string         `json:"valid_from"`
	ValidTo           sql.NullString `json:"valid_to"`
	OfficialSourceUrl string         `json:"official_source_url"`
	CreatedAt         string         `json:"created_at"`
}

type RawSnapshot struct {
	SnapshotID          string         `json:"snapshot_id"`
	AttemptID           string         `json:"attempt_id"`
	HubID               string         `json:"hub_id"`
	ResponseKind        string         `json:"response_kind"`
	ReceivedStartedAt   string         `json:"received_started_at"`
	ReceivedCompletedAt string         `json:"received_completed_at"`
	HttpStatus          int64          `json:"http_status"`
	ApiContract         sql.NullString `json:"api_contract"`
	Body                []byte         `json:"body"`
}

type RecalculationRequest struct {
	RequestID     string         `json:"request_id"`
	AuditID       string         `json:"audit_id"`
	RequestedAt   string         `json:"requested_at"`
	IntervalStart string         `json:"interval_start"`
	IntervalEnd   string         `json:"interval_end"`
	State         string         `json:"state"`
	LastError     sql.NullString `json:"last_error"`
}

type SchemaMetadatum struct {
	Singleton     int64 `json:"singleton"`
	SchemaVersion int64 `json:"schema_version"`
}

type Service struct {
	ServiceID   string         `json:"service_id"`
	Provider    string         `json:"provider"`
	Name        string         `json:"name"`
	OfficialKey string         `json:"official_key"`
	ArchivedAt  sql.NullString `json:"archived_at"`
	CreatedAt   string         `json:"created_at"`
	UpdatedAt   string         `json:"updated_at"`
}

type ServiceIdentifierMapping struct {
	MappingID      string         `json:"mapping_id"`
	IdentifierKind string         `json:"identifier_kind"`
	RawIdentifier  string         `json:"raw_identifier"`
	ServiceID      string         `json:"service_id"`
	ValidFrom      string         `json:"valid_from"`
	ValidTo        sql.NullString `json:"valid_to"`
	CreatedAt      string         `json:"created_at"`
}

type StandardPrice struct {
	StandardPriceID   string         `json:"standard_price_id"`
	PlanVersionID     string         `json:"plan_version_id"`
	UsdMonthlyPerSeat float64        `json:"usd_monthly_per_seat"`
	SourceUrl         string         `json:"source_url"`
	ValidFrom         string         `json:"valid_from"`
	ValidTo           sql.NullString `json:"valid_to"`
	CreatedAt         string         `json:"created_at"`
}

type UsageCostObservation struct {
	ObservationID             string         `json:"observation_id"`
	SnapshotID                string         `json:"snapshot_id"`
	HubID                     string         `json:"hub_id"`
	DeviceID                  string         `json:"device_id"`
	RawServiceIdentifier      string         `json:"raw_service_identifier"`
	UsageUpdatedAt            string         `json:"usage_updated_at"`
	CostUsdText               string         `json:"cost_usd_text"`
	SyncUploadIntervalMs      sql.NullInt64  `json:"sync_upload_interval_ms"`
	AnalyticsIntervalSeconds  int64          `json:"analytics_interval_seconds"`
	SourceTimezone            sql.NullString `json:"source_timezone"`
	SourceLocalDate           sql.NullString `json:"source_local_date"`
	NormalizationGeneration   int64          `json:"normalization_generation"`
	NormalizationRuleVersion  string         `json:"normalization_rule_version"`
	NormalizationLogicVersion string         `json:"normalization_logic_version"`
	JsonPath                  string         `json:"json_path"`
	DedupeState               string         `json:"dedupe_state"`
	DedupeKey                 string         `json:"dedupe_key"`
	ValueFingerprint          string         `json:"value_fingerprint"`
}

type UsageLimitObservation struct {
	ObservationID             string          `json:"observation_id"`
	SnapshotID                string          `json:"snapshot_id"`
	HubID                     string          `json:"hub_id"`
	DeviceID                  string          `json:"device_id"`
	RawServiceIdentifier      string          `json:"raw_service_identifier"`
	AccountKey                string          `json:"account_key"`
	ProviderUpdatedAt         string          `json:"provider_updated_at"`
	WindowKey                 string          `json:"window_key"`
	NormalizedKind            string          `json:"normalized_kind"`
	NormalizedMetric          string          `json:"normalized_metric"`
	NormalizedLabel           string          `json:"normalized_label"`
	PlanLabel                 string          `json:"plan_label"`
	UsedPercent               sql.NullFloat64 `json:"used_percent"`
	ResetsAt                  sql.NullString  `json:"resets_at"`
	SyncUploadIntervalMs      sql.NullInt64   `json:"sync_upload_interval_ms"`
	LimitsRefreshMs           sql.NullInt64   `json:"limits_refresh_ms"`
	AnalyticsIntervalSeconds  int64           `json:"analytics_interval_seconds"`
	SourceTimezone            sql.NullString  `json:"source_timezone"`
	SourceLocalDate           sql.NullString  `json:"source_local_date"`
	NormalizationGeneration   int64           `json:"normalization_generation"`
	NormalizationRuleVersion  string          `json:"normalization_rule_version"`
	NormalizationLogicVersion string          `json:"normalization_logic_version"`
	JsonPath                  string          `json:"json_path"`
	DedupeState               string          `json:"dedupe_state"`
	DedupeKey                 string          `json:"dedupe_key"`
	ValueFingerprint          string          `json:"value_fingerprint"`
}
