// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"database/sql"
)

type ConfigurationAudit struct {
	Sequence   int64          `json:"sequence"`
	AuditID    string         `json:"audit_id"`
	OccurredAt string         `json:"occurred_at"`
	Actor      string         `json:"actor"`
	Action     string         `json:"action"`
	EntityType string         `json:"entity_type"`
	EntityID   string         `json:"entity_id"`
	BeforeJson sql.NullString `json:"before_json"`
	AfterJson  sql.NullString `json:"after_json"`
}

type DisplaySetting struct {
	Singleton            int64          `json:"singleton"`
	Theme                string         `json:"theme"`
	DisplayTimezone      sql.NullString `json:"display_timezone"`
	TimezoneConfirmed    int64          `json:"timezone_confirmed"`
	WeekStartsOn         int64          `json:"week_starts_on"`
	CompactWindowX       sql.NullInt64  `json:"compact_window_x"`
	CompactWindowY       sql.NullInt64  `json:"compact_window_y"`
	CompactWindowWidth   sql.NullInt64  `json:"compact_window_width"`
	CompactWindowHeight  sql.NullInt64  `json:"compact_window_height"`
	CompactWindowDpi     sql.NullInt64  `json:"compact_window_dpi"`
	CompactWindowMonitor sql.NullString `json:"compact_window_monitor"`
	MainWindowX          sql.NullInt64  `json:"main_window_x"`
	MainWindowY          sql.NullInt64  `json:"main_window_y"`
	MainWindowWidth      sql.NullInt64  `json:"main_window_width"`
	MainWindowHeight     sql.NullInt64  `json:"main_window_height"`
	MainWindowDpi        sql.NullInt64  `json:"main_window_dpi"`
	MainWindowMonitor    sql.NullString `json:"main_window_monitor"`
}

type Hub struct {
	HubID                     string         `json:"hub_id"`
	DisplayName               string         `json:"display_name"`
	Url                       string         `json:"url"`
	CollectionEnabled         int64          `json:"collection_enabled"`
	CollectionIntervalSeconds int64          `json:"collection_interval_seconds"`
	ApiContract               sql.NullString `json:"api_contract"`
	CreatedAt                 string         `json:"created_at"`
	UpdatedAt                 string         `json:"updated_at"`
}

type HubConnectionStatus struct {
	HubID         string         `json:"hub_id"`
	State         string         `json:"state"`
	CheckedAt     sql.NullString `json:"checked_at"`
	FailureDetail sql.NullString `json:"failure_detail"`
}

type Judgment struct {
	EntityType string         `json:"entity_type"`
	EntityID   string         `json:"entity_id"`
	State      string         `json:"state"`
	Reason     sql.NullString `json:"reason"`
	UpdatedAt  string         `json:"updated_at"`
}

type RecalculationRequest struct {
	RequestID     string         `json:"request_id"`
	AuditID       string         `json:"audit_id"`
	RequestedAt   string         `json:"requested_at"`
	IntervalStart string         `json:"interval_start"`
	IntervalEnd   string         `json:"interval_end"`
	State         string         `json:"state"`
	LastError     sql.NullString `json:"last_error"`
}

type SchemaMetadatum struct {
	Singleton     int64 `json:"singleton"`
	SchemaVersion int64 `json:"schema_version"`
}
