// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"
)

type Querier interface {
	GetDisplaySettings(ctx context.Context) (GetDisplaySettingsRow, error)
	ListUsageCostAssociationsBySource(ctx context.Context, usageCostSourceID string) ([]UsageCostSourceAccountLink, error)
	ListUsageCostSourceCompletenessBySource(ctx context.Context, usageCostSourceID string) ([]UsageCostSourceCompleteness, error)
	ListUsageCostSourcesByHub(ctx context.Context, hubID string) ([]UsageCostSource, error)
	ListUsageLimitAssociationsBySource(ctx context.Context, usageLimitSourceID string) ([]UsageLimitSourceLink, error)
	ListUsageLimitSourcesByHub(ctx context.Context, hubID string) ([]UsageLimitSource, error)
	UpdateDisplayTimezone(ctx context.Context, arg UpdateDisplayTimezoneParams) error
	UpdateTheme(ctx context.Context, theme string) error
}

var _ Querier = (*Queries)(nil)
