// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"
)

type Querier interface {
	GetDisplaySettings(ctx context.Context) (GetDisplaySettingsRow, error)
	UpdateDisplayTimezone(ctx context.Context, arg UpdateDisplayTimezoneParams) error
	UpdateTheme(ctx context.Context, theme string) error
}

var _ Querier = (*Queries)(nil)
