// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const getDisplaySettings = `-- name: GetDisplaySettings :one
SELECT
    theme,
    display_timezone,
    timezone_confirmed,
    week_starts_on,
    compact_window_x,
    compact_window_y,
    compact_window_width,
    compact_window_height,
    compact_window_dpi,
    compact_window_monitor,
    main_window_x,
    main_window_y,
    main_window_width,
    main_window_height,
    main_window_dpi,
    main_window_monitor
FROM display_settings
WHERE singleton = 1
`

type GetDisplaySettingsRow struct {
	Theme                string         `json:"theme"`
	DisplayTimezone      sql.NullString `json:"display_timezone"`
	TimezoneConfirmed    int64          `json:"timezone_confirmed"`
	WeekStartsOn         int64          `json:"week_starts_on"`
	CompactWindowX       sql.NullInt64  `json:"compact_window_x"`
	CompactWindowY       sql.NullInt64  `json:"compact_window_y"`
	CompactWindowWidth   sql.NullInt64  `json:"compact_window_width"`
	CompactWindowHeight  sql.NullInt64  `json:"compact_window_height"`
	CompactWindowDpi     sql.NullInt64  `json:"compact_window_dpi"`
	CompactWindowMonitor sql.NullString `json:"compact_window_monitor"`
	MainWindowX          sql.NullInt64  `json:"main_window_x"`
	MainWindowY          sql.NullInt64  `json:"main_window_y"`
	MainWindowWidth      sql.NullInt64  `json:"main_window_width"`
	MainWindowHeight     sql.NullInt64  `json:"main_window_height"`
	MainWindowDpi        sql.NullInt64  `json:"main_window_dpi"`
	MainWindowMonitor    sql.NullString `json:"main_window_monitor"`
}

func (q *Queries) GetDisplaySettings(ctx context.Context) (GetDisplaySettingsRow, error) {
	row := q.db.QueryRowContext(ctx, getDisplaySettings)
	var i GetDisplaySettingsRow
	err := row.Scan(
		&i.Theme,
		&i.DisplayTimezone,
		&i.TimezoneConfirmed,
		&i.WeekStartsOn,
		&i.CompactWindowX,
		&i.CompactWindowY,
		&i.CompactWindowWidth,
		&i.CompactWindowHeight,
		&i.CompactWindowDpi,
		&i.CompactWindowMonitor,
		&i.MainWindowX,
		&i.MainWindowY,
		&i.MainWindowWidth,
		&i.MainWindowHeight,
		&i.MainWindowDpi,
		&i.MainWindowMonitor,
	)
	return i, err
}

const updateDisplayTimezone = `-- name: UpdateDisplayTimezone :exec
UPDATE display_settings
SET
    display_timezone = ?1,
    timezone_confirmed = ?2
WHERE singleton = 1
`

type UpdateDisplayTimezoneParams struct {
	DisplayTimezone   sql.NullString `json:"display_timezone"`
	TimezoneConfirmed int64          `json:"timezone_confirmed"`
}

func (q *Queries) UpdateDisplayTimezone(ctx context.Context, arg UpdateDisplayTimezoneParams) error {
	_, err := q.db.ExecContext(ctx, updateDisplayTimezone, arg.DisplayTimezone, arg.TimezoneConfirmed)
	return err
}

const updateTheme = `-- name: UpdateTheme :exec
UPDATE display_settings
SET theme = ?1
WHERE singleton = 1
`

func (q *Queries) UpdateTheme(ctx context.Context, theme string) error {
	_, err := q.db.ExecContext(ctx, updateTheme, theme)
	return err
}
