// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Observation {
    "provider": string;
    "accountKey": string;
    "accountLabel": string;
    "windowKind": string;
    "windowLabel": string;
    "periodKey": string;
    "periodStart": string;
    "periodEnd": string;
    "resetAt": string;
    "usageUsd": number;
    "utilizationPercent": number;
    "estimatedLimitUsd": number;
    "calculationStatus": string;
    "calculationNote": string;
    "observedAt": string;
    "calculatedAt": string;
}

export interface UsageBreakdown {
    "dimension": string;
    "key": string;
    "label": string;
    "tokens": number;
    "costUsd": number;
}
