// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface AccountOption {
    "provider": string;
    "accountKey": string;
    "accountLabel": string;
}

export interface Subscription {
    "id": number;
    "provider": string;
    "accountKey": string;
    "accountLabel": string;
    "planName": string;
    "monthlyPriceUsd": number;
    "updatedAt": string;
}
