// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AccountService is the Wails boundary for M05. It exposes account evidence
 * and explicit logical-account decisions without exposing domain structs.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function ArchiveLogicalAccount(accountID: string): $CancellablePromise<void> {
    return $Call.ByID(2355882583, accountID);
}

export function AssociateHubAccountCandidate(candidateID: string, logicalAccountID: string): $CancellablePromise<void> {
    return $Call.ByID(1769254192, candidateID, logicalAccountID);
}

export function ConfirmHubSwitch(input: $models.HubSwitchInput): $CancellablePromise<$models.HubSwitchSnapshot> {
    return $Call.ByID(1101677674, input);
}

export function ConfirmUsageCostSourceCompleteness(input: $models.UsageCostSourceCompletenessInput): $CancellablePromise<$models.UsageCostSourceCompletenessSnapshot> {
    return $Call.ByID(3052602698, input);
}

export function CreateLogicalAccount(input: $models.CreateLogicalAccountInput): $CancellablePromise<$models.LogicalAccountSnapshot> {
    return $Call.ByID(1045424751, input);
}

export function CreateLogicalAccountFromCandidate(input: $models.CreateLogicalAccountFromCandidateInput): $CancellablePromise<$models.LogicalAccountSnapshot> {
    return $Call.ByID(1130295076, input);
}

export function CreatePlanHistory(input: $models.CreatePlanHistoryInput): $CancellablePromise<$models.PlanHistorySnapshot> {
    return $Call.ByID(1963657406, input);
}

export function CreateUsageCostAssociation(input: $models.UsageCostAssociationInput): $CancellablePromise<$models.UsageCostAssociationSnapshot> {
    return $Call.ByID(636840432, input);
}

export function CreateUsageLimitAssociation(input: $models.UsageLimitAssociationInput): $CancellablePromise<$models.UsageLimitAssociationSnapshot> {
    return $Call.ByID(4128043978, input);
}

export function GetAccounts(): $CancellablePromise<$models.AccountSnapshot> {
    return $Call.ByID(774551111);
}

export function GetHubAccountCandidates(serviceID: string, state: string): $CancellablePromise<$models.HubAccountCandidateSnapshot[] | null> {
    return $Call.ByID(1199573395, serviceID, state);
}

export function GetLinkingSnapshot(): $CancellablePromise<$models.LinkingSnapshot> {
    return $Call.ByID(3619603625);
}

export function GetLogicalAccounts(serviceID: string, includeArchived: boolean): $CancellablePromise<$models.LogicalAccountSnapshot[] | null> {
    return $Call.ByID(2770531066, serviceID, includeArchived);
}

export function GetPlanHistories(logicalAccountID: string): $CancellablePromise<$models.PlanHistorySnapshot[] | null> {
    return $Call.ByID(1704574112, logicalAccountID);
}

export function MergeLogicalAccounts(sourceID: string, targetID: string): $CancellablePromise<void> {
    return $Call.ByID(3506941314, sourceID, targetID);
}

export function PreviewHubSwitch(input: $models.HubSwitchInput): $CancellablePromise<$models.ImpactPreviewSnapshot> {
    return $Call.ByID(1835284450, input);
}

export function PreviewUsageCostAssociation(input: $models.UsageCostAssociationInput): $CancellablePromise<$models.ImpactPreviewSnapshot> {
    return $Call.ByID(767914646, input);
}

export function PreviewUsageCostSourceCompleteness(input: $models.UsageCostSourceCompletenessInput): $CancellablePromise<$models.ImpactPreviewSnapshot> {
    return $Call.ByID(2883949874, input);
}

export function PreviewUsageLimitAssociation(input: $models.UsageLimitAssociationInput): $CancellablePromise<$models.ImpactPreviewSnapshot> {
    return $Call.ByID(3204980576, input);
}

export function RejectHubAccountCandidate(candidateID: string): $CancellablePromise<void> {
    return $Call.ByID(2409683429, candidateID);
}

export function ReleaseHubAccountCandidate(candidateID: string): $CancellablePromise<void> {
    return $Call.ByID(2893049229, candidateID);
}

export function RestoreLogicalAccount(accountID: string): $CancellablePromise<void> {
    return $Call.ByID(2002298179, accountID);
}

export function SplitLogicalAccount(input: $models.SplitLogicalAccountInput): $CancellablePromise<$models.LogicalAccountSnapshot> {
    return $Call.ByID(4105751825, input);
}

export function UpdateLogicalAccount(input: $models.UpdateLogicalAccountInput): $CancellablePromise<void> {
    return $Call.ByID(3681121670, input);
}

export function UpdatePlanHistory(input: $models.UpdatePlanHistoryInput): $CancellablePromise<void> {
    return $Call.ByID(1701591733, input);
}

export function UpdateUsageCostAssociation(input: $models.UsageCostAssociationInput): $CancellablePromise<void> {
    return $Call.ByID(352947873, input);
}

export function UpdateUsageCostSourceCompleteness(input: $models.UsageCostSourceCompletenessInput): $CancellablePromise<void> {
    return $Call.ByID(3554310483, input);
}

export function UpdateUsageLimitAssociation(input: $models.UsageLimitAssociationInput): $CancellablePromise<void> {
    return $Call.ByID(3764110637, input);
}
