// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AuditService exposes only read operations for M10. The adapter owns query
 * ordering, cursor validation, and JSON redaction; this layer translates the
 * Wails DTO and validates user-entered date boundaries.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function GetAudits(input: $models.AuditFilterInput): $CancellablePromise<$models.AuditPage> {
    return $Call.ByID(8461583, input);
}
