// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CatalogService is the Wails boundary for M06. Raw identifiers and reported
 * names are returned exactly as stored; this service never guesses a product
 * catalog from a string.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function ArchiveService(serviceID: string): $CancellablePromise<void> {
    return $Call.ByID(70937400, serviceID);
}

export function ConfirmIdentificationCandidate(input: $models.CandidateDecisionInput): $CancellablePromise<void> {
    return $Call.ByID(3229932090, input);
}

export function CorrectIdentificationCandidate(input: $models.CandidateCorrectionInput): $CancellablePromise<void> {
    return $Call.ByID(3472655188, input);
}

export function CreateLimitDefinition(input: $models.LimitDefinitionInput): $CancellablePromise<void> {
    return $Call.ByID(311861553, input);
}

export function CreatePlan(input: $models.PlanInput): $CancellablePromise<void> {
    return $Call.ByID(1709918686, input);
}

export function CreatePlanLimitRule(input: $models.PlanLimitRuleInput): $CancellablePromise<void> {
    return $Call.ByID(4260239275, input);
}

export function CreatePlanVersion(input: $models.PlanVersionInput): $CancellablePromise<void> {
    return $Call.ByID(3999755298, input);
}

export function CreateService(input: $models.CreateServiceInput): $CancellablePromise<$models.ServiceSnapshot> {
    return $Call.ByID(975992512, input);
}

export function CreateServiceIdentifierMapping(input: $models.ServiceIdentifierMappingInput): $CancellablePromise<void> {
    return $Call.ByID(426687383, input);
}

export function CreateStandardPrice(input: $models.StandardPriceInput): $CancellablePromise<void> {
    return $Call.ByID(3538390081, input);
}

export function DecideLabelChangeCandidate(input: $models.LabelChangeDecisionInput): $CancellablePromise<void> {
    return $Call.ByID(1904116562, input);
}

export function GetCatalog(): $CancellablePromise<$models.CatalogSnapshot> {
    return $Call.ByID(1386883966);
}

export function GetIdentificationCandidates(state: string): $CancellablePromise<$models.IdentificationCandidateSnapshot[] | null> {
    return $Call.ByID(2477733675, state);
}

export function GetLabelChangeCandidates(state: string): $CancellablePromise<$models.LabelChangeCandidateSnapshot[] | null> {
    return $Call.ByID(2467967481, state);
}

export function GetLimitDefinitions(includeArchived: boolean): $CancellablePromise<$models.LimitDefinitionSnapshot[] | null> {
    return $Call.ByID(554389052, includeArchived);
}

export function GetPlanLimitRules(planVersionID: string): $CancellablePromise<$models.PlanLimitRuleSnapshot[] | null> {
    return $Call.ByID(2218225702, planVersionID);
}

export function GetPlanVersions(planID: string): $CancellablePromise<$models.PlanVersionSnapshot[] | null> {
    return $Call.ByID(1563064809, planID);
}

export function GetPlans(serviceID: string, includeArchived: boolean): $CancellablePromise<$models.PlanSnapshot[] | null> {
    return $Call.ByID(2887610605, serviceID, includeArchived);
}

export function GetServiceIdentifierMappings(kind: string): $CancellablePromise<$models.ServiceIdentifierMappingSnapshot[] | null> {
    return $Call.ByID(1355156994, kind);
}

export function GetServices(includeArchived: boolean): $CancellablePromise<$models.ServiceSnapshot[] | null> {
    return $Call.ByID(214175007, includeArchived);
}

export function GetStandardPrices(planVersionID: string): $CancellablePromise<$models.StandardPriceSnapshot[] | null> {
    return $Call.ByID(2205166672, planVersionID);
}

export function RejectIdentificationCandidate(candidateID: string): $CancellablePromise<void> {
    return $Call.ByID(648196521, candidateID);
}

export function ReleaseIdentificationCandidate(candidateID: string): $CancellablePromise<void> {
    return $Call.ByID(2312760577, candidateID);
}

export function RestoreService(serviceID: string): $CancellablePromise<void> {
    return $Call.ByID(3329727412, serviceID);
}

export function SetBaselinePlan(serviceID: string, planID: string): $CancellablePromise<void> {
    return $Call.ByID(2729452251, serviceID, planID);
}

export function SetBillingConfirmation(definitionID: string, confirmation: string): $CancellablePromise<void> {
    return $Call.ByID(4022235887, definitionID, confirmation);
}

export function SplitIdentificationCandidate(input: $models.CandidateSplitInput): $CancellablePromise<void> {
    return $Call.ByID(4225449326, input);
}

export function UpdateLimitDefinition(input: $models.LimitDefinitionInput): $CancellablePromise<void> {
    return $Call.ByID(2525863934, input);
}

export function UpdatePlan(input: $models.PlanInput): $CancellablePromise<void> {
    return $Call.ByID(605397555, input);
}

export function UpdateService(input: $models.UpdateServiceInput): $CancellablePromise<$models.ServiceSnapshot> {
    return $Call.ByID(2724673171, input);
}

export function UpdateServiceIdentifierMapping(input: $models.ServiceIdentifierMappingInput): $CancellablePromise<void> {
    return $Call.ByID(483690134, input);
}
