// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CollectNow delegates a manual collection to the scheduler/usecase. The
 * result, including a disabled or duplicate-in-flight skip, is persisted in
 * the attempt history by that layer.
 */
export function CollectNow(hubID: string): $CancellablePromise<void> {
    return $Call.ByID(982940882, hubID);
}

/**
 * GetCollectionAttempts returns the M07 acquisition history without exposing
 * credentials or arbitrary error detail.
 */
export function GetCollectionAttempts(hubID: string): $CancellablePromise<$models.CollectionAttemptSnapshot[] | null> {
    return $Call.ByID(274495694, hubID);
}

/**
 * GetCostObservations returns normalized usage-cost source observations.
 */
export function GetCostObservations(hubID: string): $CancellablePromise<$models.CostObservationSnapshot[] | null> {
    return $Call.ByID(97405014, hubID);
}

/**
 * GetLimitObservations returns normalized usage-limit source observations.
 */
export function GetLimitObservations(hubID: string): $CancellablePromise<$models.LimitObservationSnapshot[] | null> {
    return $Call.ByID(154133356, hubID);
}

/**
 * GetRawSnapshot returns a masked viewer representation. The persisted bytes
 * are never returned through a Wails DTO; usecase/SQLite retain them for
 * evidence and exactness tests.
 */
export function GetRawSnapshot(snapshotID: string): $CancellablePromise<$models.RawSnapshotDetail> {
    return $Call.ByID(1845356702, snapshotID);
}

/**
 * GetRawSnapshots returns M08 snapshot metadata only. Body is deliberately
 * absent from this DTO; callers must request one explicit detail.
 */
export function GetRawSnapshots(hubID: string): $CancellablePromise<$models.RawSnapshotSnapshot[] | null> {
    return $Call.ByID(330673431, hubID);
}

/**
 * StartCollection enables collection and starts the scheduler job for one
 * Hub. Disabled-Hub validation remains in the collection usecase/scheduler.
 */
export function StartCollection(hubID: string): $CancellablePromise<void> {
    return $Call.ByID(2498670080, hubID);
}

/**
 * StopCollection disables collection and cancels the scheduler job for one
 * Hub.
 */
export function StopCollection(hubID: string): $CancellablePromise<void> {
    return $Call.ByID(1991542324, hubID);
}
