// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DataManagementService is the M09 input adapter. It deliberately exposes no
 * database entities, raw errors, secrets, or credential-store facts. The
 * user-selected backup output path is returned as an artifact fact.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function ApplyPurge(input: $models.DataManagementPurgeSelectionInput, confirmed: boolean): $CancellablePromise<$models.DataManagementPurgeStateSnapshot> {
    return $Call.ByID(2874237880, input, confirmed);
}

export function ApplyRestore(operationID: string, confirmed: boolean): $CancellablePromise<$models.DataManagementRestoreApplyStateSnapshot> {
    return $Call.ByID(3450655181, operationID, confirmed);
}

export function CancelCurrentOperation(): $CancellablePromise<$models.DataManagementCancellationSnapshot> {
    return $Call.ByID(1508469891);
}

export function CreateBackup(destinationPath: string): $CancellablePromise<$models.DataManagementBackupStateSnapshot> {
    return $Call.ByID(802755493, destinationPath);
}

export function GetCapacity(): $CancellablePromise<$models.DataManagementCapacityResultSnapshot> {
    return $Call.ByID(2750739549);
}

export function GetMaintenanceState(): $CancellablePromise<$models.DataManagementMaintenanceSnapshot> {
    return $Call.ByID(347950657);
}

export function GetRecoveryNotice(): $CancellablePromise<$models.DataManagementRecoveryNoticeSnapshot> {
    return $Call.ByID(3633213762);
}

export function GetRestoreState(): $CancellablePromise<$models.DataManagementRestoreStateSnapshot> {
    return $Call.ByID(477406150);
}

export function GetState(): $CancellablePromise<$models.DataManagementStateSnapshot> {
    return $Call.ByID(1201249874);
}

export function PreviewPurge(input: $models.DataManagementPurgeSelectionInput): $CancellablePromise<$models.DataManagementPurgeStateSnapshot> {
    return $Call.ByID(3948219344, input);
}

export function RunRestoreTrial(operationID: string): $CancellablePromise<$models.DataManagementRestoreTrialStateSnapshot> {
    return $Call.ByID(2688455350, operationID);
}

export function ValidateRestore(archivePath: string): $CancellablePromise<$models.DataManagementRestoreValidationStateSnapshot> {
    return $Call.ByID(234640589, archivePath);
}
