// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function GetLimitSeries(input: $models.LimitSeriesFilterInput): $CancellablePromise<$models.LimitSeriesSnapshot[] | null> {
    return $Call.ByID(1931782045, input);
}

export function GetLimitSeriesDetail(seriesID: string): $CancellablePromise<$models.LimitSeriesDetailSnapshot> {
    return $Call.ByID(1289894284, seriesID);
}
