// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CheckHubConnection(hubID: string): $CancellablePromise<$models.HubSnapshot> {
    return $Call.ByID(1373773394, hubID);
}

export function CreateHub(input: $models.CreateHubInput): $CancellablePromise<$models.HubSnapshot> {
    return $Call.ByID(1545926396, input);
}

export function DeleteCredential(hubID: string): $CancellablePromise<$models.HubSnapshot> {
    return $Call.ByID(1597424207, hubID);
}

export function GetHub(hubID: string): $CancellablePromise<$models.HubSnapshot> {
    return $Call.ByID(1997514630, hubID);
}

export function GetHubs(): $CancellablePromise<$models.HubSnapshot[] | null> {
    return $Call.ByID(1655006895);
}

export function SaveCredential(hubID: string, secret: string): $CancellablePromise<$models.HubSnapshot> {
    return $Call.ByID(3695003153, hubID, secret);
}

export function SetHubCollectionEnabled(hubID: string, enabled: boolean): $CancellablePromise<$models.HubSnapshot> {
    return $Call.ByID(3831218191, hubID, enabled);
}

export function UpdateHub(input: $models.UpdateHubInput): $CancellablePromise<$models.HubSnapshot> {
    return $Call.ByID(3150729307, input);
}
