// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface AccountSnapshot {
    "hubAccountCandidates": HubAccountCandidateSnapshot[] | null;
    "logicalAccounts": LogicalAccountSnapshot[] | null;
    "planHistories": PlanHistorySnapshot[] | null;
}

export interface AuditFilterInput {
    "cursor": string;
    "limit": number;
    "from": string;
    "to": string;
    "entityType": string;
    "action": string;
}

export interface AuditPage {
    "items": AuditRecord[] | null;
    "nextCursor": string;
    "hasMore": boolean;
}

export interface AuditRecord {
    "sequence": number;
    "auditId": string;
    "occurredAt": string;
    "actor": string;
    "action": string;
    "entityType": string;
    "entityId": string;
    "beforeJson": string;
    "afterJson": string;
}

export interface CalculationBoundarySnapshot {
    "id": string;
    "kindCode": string;
    "kind": string;
    "at": string;
    "reason": string;
    "relatedId": string;
}

export interface CalculationIntervalSnapshot {
    "id": string;
    "serviceId": string;
    "logicalAccountId": string;
    "usageLimitSourceId": string;
    "limitDefinitionId": string;
    "planVersionId": string;
    "cycleType": string;
    "validFrom": string;
    "validTo": string;
    "state": string;
    "stateLabel": string;
    "exclusionReasonCode": string;
    "exclusionReason": string;
    "boundaryIds": string[] | null;
    "boundaries": CalculationBoundarySnapshot[] | null;
    "role": string;
    "roleLabel": string;
    "estimatedLimit": number | null;
    "estimatedLimitLabel": string;
    "monthlyEquivalentLimit": number | null;
    "monthlyEquivalentLimitLabel": string;
    "standardPriceUsdMonthlyPerSeat": number | null;
    "standardPriceSourceUrl": string;
    "standardPriceValidFrom": string;
    "standardPriceValidTo": string;
    "valueMultiplier": number | null;
    "valueMultiplierLabel": string;
    "valueReasonCode": string;
    "valueReason": string;
}

export interface CalendarPeriodUsageInput {
    "displayTimeZone": string;
}

export interface CalendarPeriodUsageSnapshot {
    "displayTimeZone": string;
    "day": CalendarPeriodValueSnapshot;
    "month": CalendarPeriodValueSnapshot;
}

export interface CalendarPeriodValueSnapshot {
    "available": boolean;
    "periodKind": string;
    "periodKey": string;
    "tokens": number;
    "apiCostUsd": number;
    "apiCostUsdText": string;
    "latestObservedAt": string;
    "oldestObservedAt": string;
    "deviceCount": number;
    "unavailableReason": string;
}

export interface CandidateCorrectionInput {
    "candidateId": string;
    "rawLimitServiceIdentifier": string;
    "rawReportedPlanName": string;
}

export interface CandidateDecisionInput {
    "candidateId": string;
    "serviceId": string;
    "planId": string;
}

export interface CandidateObservationSnapshot {
    "id": string;
    "candidateId": string;
    "hubId": string;
    "hubAccountDisplay": string;
    "observedAt": string;
}

export interface CandidateSplitInput {
    "sourceCandidateId": string;
    "rawLimitServiceIdentifier": string;
    "rawReportedPlanName": string;
    "observationIds": string[] | null;
}

export interface CatalogSnapshot {
    "services": ServiceSnapshot[] | null;
    "serviceIdentifierMappings": ServiceIdentifierMappingSnapshot[] | null;
    "limitDefinitions": LimitDefinitionSnapshot[] | null;
    "plans": PlanSnapshot[] | null;
    "planVersions": PlanVersionSnapshot[] | null;
    "planLimitRules": PlanLimitRuleSnapshot[] | null;
    "standardPrices": StandardPriceSnapshot[] | null;
    "identificationCandidates": IdentificationCandidateSnapshot[] | null;
    "labelChangeCandidates": LabelChangeCandidateSnapshot[] | null;
}

export interface CollectionAttemptSnapshot {
    "attemptId": string;
    "hubId": string;
    "trigger": string;
    "state": string;
    "startedAt": string;
    "completedAt": string;
    "analyticsIntervalSeconds": number;
    "healthHttpStatus"?: number | null;
    "statsHttpStatus"?: number | null;
    "apiContract": string;
    "healthSnapshotId": string;
    "statsSnapshotId": string;
    "failureCode": string;
    "failureDetail": string;
    "normalizationErrorPath": string;
}

export interface CostObservationSnapshot {
    "observationId": string;
    "snapshotId": string;
    "hubId": string;
    "deviceId": string;
    "rawServiceIdentifier": string;
    "usageUpdatedAt": string;
    "costUsdText": string;
    "syncUploadIntervalMs"?: number | null;
    "analyticsIntervalSeconds": number;
    "sourceTimezone": string;
    "sourceLocalDate": string;
    "normalizationGeneration": number;
    "normalizationRuleVersion": string;
    "normalizationLogicVersion": string;
    "jsonPath": string;
    "dedupeState": string;
    "dedupeKey": string;
    "valueFingerprint": string;
    "occurrenceCount"?: number;
    "firstSeenAt"?: string;
    "lastSeenAt"?: string;
    "lastSeenSnapshotId"?: string;
}

export interface CreateHubInput {
    "displayName": string;
    "url": string;
    "collectionIntervalSeconds": number;
    "collectionEnabled": boolean;
    "secret": string;
}

export interface CreateLogicalAccountFromCandidateInput {
    "candidateId": string;
    "serviceId": string;
    "displayName": string;
}

export interface CreateLogicalAccountInput {
    "serviceId": string;
    "displayName": string;
}

export interface CreatePlanHistoryInput {
    "logicalAccountId": string;
    "planVersionId": string;
    "validFrom": string;
    "validTo": string;
}

export interface CreateServiceInput {
    "provider": string;
    "name": string;
    "officialKey": string;
}

export interface DataManagementArtifactSnapshot {
    "path": string;
    "artifactSha256": string;
    "sizeBytes": number;
    "formatVersion": number;
    "schemaVersion": number;
    "appVersion": string;
    "createdAt": string;
    "warning": string;
}

export interface DataManagementBackupStateSnapshot {
    "status": string;
    "cancelAllowed": boolean;
    "artifact": DataManagementArtifactSnapshot | null;
    "error": DataManagementErrorSnapshot | null;
}

export interface DataManagementCancellationSnapshot {
    "status": string;
    "phase": string;
    "cancelAllowed": boolean;
    "cancellationBoundary": string;
    "message": string;
    "error": DataManagementErrorSnapshot | null;
}

export interface DataManagementCapacityResultSnapshot {
    "status": string;
    "capacity": DataManagementCapacitySnapshot | null;
    "error": DataManagementErrorSnapshot | null;
}

export interface DataManagementCapacitySnapshot {
    "databaseSizeBytes": number;
    "rawSnapshotCount": number;
    "oldestCompletedAt": string;
    "latestCompletedAt": string;
    "rawJsonBytes": number;
}

export interface DataManagementErrorSnapshot {
    "code": string;
    "message": string;
    "details": string[] | null;
    "rolledBack": boolean;
    "currentDataUnchanged": boolean;
}

export interface DataManagementMaintenanceSnapshot {
    "active": boolean;
    "operation": string;
    "phase": string;
    "cancelAllowed": boolean;
    "cancellationBoundary": string;
}

export interface DataManagementPurgePreviewSnapshot {
    "selection": DataManagementPurgeSelectionSnapshot;
    "capacity": DataManagementCapacitySnapshot;
    "requiredConfirmationText": string;
}

export interface DataManagementPurgeResultSnapshot {
    "auditId": string;
    "executedAt": string;
    "rawSnapshotCount": number;
    "costObservationCount": number;
    "limitObservationCount": number;
    "matchedObservationCount": number;
    "estimationPointCount": number;
    "estimationResultCount": number;
    "estimationEvidenceCount": number;
    "calculationIntervalCount": number;
    "calculationBoundaryCount": number;
    "recalculatedResultCount": number;
}

export interface DataManagementPurgeSelectionInput {
    "allHubs": boolean;
    "hubIds": string[] | null;
    "startAt": string;
    "endAt": string;
    "confirmationText": string;
}

export interface DataManagementPurgeSelectionSnapshot {
    "allHubs": boolean;
    "hubIds": string[] | null;
    "startAt": string;
    "endAt": string;
}

export interface DataManagementPurgeStateSnapshot {
    "status": string;
    "cancelAllowed": boolean;
    "preview": DataManagementPurgePreviewSnapshot | null;
    "result": DataManagementPurgeResultSnapshot | null;
    "error": DataManagementErrorSnapshot | null;
}

export interface DataManagementRecoveryNoticeSnapshot {
    "status": string;
    "artifactSha256": string;
    "message": string;
}

export interface DataManagementRestoreApplyStateSnapshot {
    "status": string;
    "phase": string;
    "cancelAllowed": boolean;
    "cancellationBoundary": string;
    "operationId": string;
    "artifact": DataManagementArtifactSnapshot | null;
    "restoredAt": string;
    "auditId": string;
    "rollbackSucceeded": boolean;
    "warning": string;
    "credentialState": string;
    "requiresCredentialReregistration": boolean;
    "error": DataManagementErrorSnapshot | null;
}

export interface DataManagementRestoreStateSnapshot {
    "validation": DataManagementRestoreValidationStateSnapshot;
    "trial": DataManagementRestoreTrialStateSnapshot;
    "apply": DataManagementRestoreApplyStateSnapshot;
}

export interface DataManagementRestoreTrialStateSnapshot {
    "status": string;
    "cancelAllowed": boolean;
    "artifactSha256": string;
    "testedAt": string;
    "warning": string;
    "error": DataManagementErrorSnapshot | null;
}

export interface DataManagementRestoreValidationStateSnapshot {
    "status": string;
    "cancelAllowed": boolean;
    "applyAllowed": boolean;
    "operationId": string;
    "artifact": DataManagementArtifactSnapshot | null;
    "error": DataManagementErrorSnapshot | null;
}

export interface DataManagementStateSnapshot {
    "capacity": DataManagementCapacityResultSnapshot;
    "purge": DataManagementPurgeStateSnapshot;
    "backup": DataManagementBackupStateSnapshot;
    "restore": DataManagementRestoreStateSnapshot;
    "recovery": DataManagementRecoveryNoticeSnapshot;
    "maintenance": DataManagementMaintenanceSnapshot;
}

export interface EstimationDifferenceRowSnapshot {
    "id": string;
    "startPointId": string;
    "endPointId": string;
    "startAt": string;
    "endAt": string;
    "coefficients": number[] | null;
    "cost": number;
    "accepted": boolean;
    "exclusionReasonCode": string;
    "exclusionReason": string;
}

export interface EstimationEvidenceSnapshot {
    "id": string;
    "kind": string;
    "pointId": string;
    "sourceId": string;
    "observationId": string;
    "snapshotId": string;
    "associationId": string;
    "completenessId": string;
    "planHistoryId": string;
    "logicalAccountId": string;
    "planVersionId": string;
    "observedAt": string;
    "timeDelta": string;
    "normalizationGeneration": number;
    "normalizationRuleVersion": string;
    "normalizationLogicVersion": string;
    "detailsJson": string;
    "m08Route": string;
}

export interface EstimationReferenceSnapshot {
    "resultId": string;
    "status": StatusPresentationSnapshot;
    "validFrom": string;
    "validTo": string;
    "age": string;
    "observedAt": string;
}

export interface EstimationResultSnapshot {
    "id": string;
    "resultSetKey": string;
    "status": StatusPresentationSnapshot;
    "statusReasonCode": string;
    "statusReason": string;
    "limits": number[] | null;
    "observationPointCount": number;
    "differenceRowCount": number;
    "rank": number;
    "absoluteErrorRatio": number;
    "absoluteErrorRatioLabel": string;
    "maxTimeDelta": string;
    "calculationLogicVersion": string;
    "matchingRuleVersion": string;
    "inputFingerprint": string;
    "calculationIntervalIds": string[] | null;
    "validFrom": string;
    "validTo": string;
    "differenceRows": EstimationDifferenceRowSnapshot[] | null;
    "evidence": EstimationEvidenceSnapshot[] | null;
}

export interface HubAccountCandidateSnapshot {
    "id": string;
    "hubId": string;
    "serviceId": string;
    "accountKey": string;
    "displayName": string;
    "email": string;
    "workspaceName": string;
    "deviceName": string;
    "state": string;
    "logicalAccountId": string;
    "firstObservedAt": string;
    "lastObservedAt": string;
    "createdAt": string;
    "updatedAt": string;
}

export interface HubSnapshot {
    "id": string;
    "displayName": string;
    "url": string;
    "enabled": boolean;
    "collectionEnabled": boolean;
    "collectionIntervalSeconds": number;
    "apiContract": string;
    "credentialState": string;
    "credentialReady": boolean;
    "connectionState": string;
    "connectionCheckedAt": string;
    "connectionFailureNote": string;
}

export interface HubSwitchInput {
    "id": string;
    "oldHubId": string;
    "oldDeviceId": string;
    "newHubId": string;
    "newDeviceId": string;
    "collectionDeviceId": string;
    "switchedAt": string;
}

export interface HubSwitchSnapshot {
    "id": string;
    "oldHubId": string;
    "oldDeviceId": string;
    "newHubId": string;
    "newDeviceId": string;
    "collectionDeviceId": string;
    "switchedAt": string;
    "createdAt": string;
}

export interface IdentificationCandidateSnapshot {
    "id": string;
    "rawLimitServiceIdentifier": string;
    "rawReportedPlanName": string;
    "state": string;
    "serviceId": string;
    "planId": string;
    "firstObservedAt": string;
    "lastObservedAt": string;
    "createdAt": string;
    "updatedAt": string;
    "observations": CandidateObservationSnapshot[] | null;
}

export interface ImpactIntervalSnapshot {
    "start": string;
    "end": string;
}

export interface ImpactPreviewSnapshot {
    "sourceId": string;
    "sourceKind": string;
    "intervalStart": string;
    "intervalEnd": string;
    "affectedObservationIds": string[] | null;
    "affectedCalculationIntervals": ImpactIntervalSnapshot[] | null;
    "affectedDerivedResultIds": string[] | null;
}

export interface LabelChangeCandidateSnapshot {
    "id": string;
    "hubId": string;
    "deviceRecordKey": string;
    "hubAccountKey": string;
    "rawLimitServiceIdentifier": string;
    "normalizedKind": string;
    "normalizedMetric": string;
    "oldLabel": string;
    "newLabel": string;
    "state": string;
    "limitDefinitionId": string;
    "firstObservedAt": string;
    "lastObservedAt": string;
    "createdAt": string;
    "updatedAt": string;
    "windows": LabelChangeWindowSnapshot[] | null;
}

export interface LabelChangeDecisionInput {
    "candidateId": string;
    "state": string;
    "limitDefinitionId": string;
}

export interface LabelChangeWindowSnapshot {
    "id": string;
    "candidateId": string;
    "windowKey": string;
    "label": string;
    "observedAt": string;
}

export interface LimitDefinitionInput {
    "id": string;
    "serviceId": string;
    "cycleType": string;
    "meaning": string;
    "unit": string;
    "billingConfirmation": string;
}

export interface LimitDefinitionSnapshot {
    "id": string;
    "serviceId": string;
    "cycleType": string;
    "meaning": string;
    "unit": string;
    "billingConfirmation": string;
    "archivedAt": string;
    "createdAt": string;
    "updatedAt": string;
}

export interface LimitObservationSnapshot {
    "observationId": string;
    "snapshotId": string;
    "hubId": string;
    "deviceId": string;
    "rawServiceIdentifier": string;
    "accountKey": string;
    "providerUpdatedAt": string;
    "windowKey": string;
    "normalizedKind": string;
    "normalizedMetric": string;
    "normalizedLabel": string;
    "planLabel": string;
    "usedPercent"?: number | null;
    "remainingPercent"?: number | null;
    "resetsAt": string;
    "syncUploadIntervalMs"?: number | null;
    "limitsRefreshMs"?: number | null;
    "analyticsIntervalSeconds": number;
    "sourceTimezone": string;
    "sourceLocalDate": string;
    "normalizationGeneration": number;
    "normalizationRuleVersion": string;
    "normalizationLogicVersion": string;
    "jsonPath": string;
    "dedupeState": string;
    "dedupeKey": string;
    "valueFingerprint": string;
    "windowKeyConflict": boolean;
    "occurrenceCount"?: number;
    "firstSeenAt"?: string;
    "lastSeenAt"?: string;
    "lastSeenSnapshotId"?: string;
}

export interface LimitSeriesDetailSnapshot {
    "series": LimitSeriesSnapshot;
    "current": CalculationIntervalSnapshot | null;
    "history": CalculationIntervalSnapshot[] | null;
}

export interface LimitSeriesFilterInput {
    "serviceId": string;
    "status": string;
    "planVersionId": string;
    "limitDefinitionId": string;
    "sortBy": string;
    "descending": boolean;
}

export interface LimitSeriesSnapshot {
    "id": string;
    "serviceId": string;
    "serviceName": string;
    "logicalAccountId": string;
    "logicalAccountName": string;
    "limitDefinitionId": string;
    "limitDefinitionName": string;
    "cycleType": string;
    "billingConfirmation": string;
    "usageLimitSourceId": string;
    "associationId": string;
    "normalizedKind": string;
    "normalizedMetric": string;
    "planHistoryId": string;
    "planVersionId": string;
    "planVersionName": string;
    "planLimitRuleId": string;
    "planLimit": number | null;
    "planLimitLabel": string;
    "multiplier": number | null;
    "usedPercent": number | null;
    "usedPercentLabel": string;
    "usedPercentDetailLabel": string;
    "remainingPercent": number | null;
    "remainingLabel": string;
    "remainingDetailLabel": string;
    "resetAt": string;
    "latestObservationAt": string;
    "seriesState": string;
    "state": StatusPresentationSnapshot;
    "stateReasonCode": string;
    "stateReason": string;
    "currentInterval": CalculationIntervalSnapshot | null;
    "result": EstimationResultSnapshot | null;
    "latestValidReference": EstimationReferenceSnapshot | null;
    "estimatedLimit": number | null;
    "estimatedLimitLabel": string;
    "monthlyEquivalentLimit": number | null;
    "monthlyEquivalentLimitLabel": string;
    "standardPriceUsdMonthlyPerSeat": number | null;
    "standardPriceSourceUrl": string;
    "standardPriceValidFrom": string;
    "standardPriceValidTo": string;
    "valueMultiplier": number | null;
    "valueMultiplierLabel": string;
    "valueReasonCode": string;
    "valueReason": string;
}

export interface LinkingSnapshot {
    "usageCostSources": UsageCostSourceSnapshot[] | null;
    "usageLimitSources": UsageLimitSourceSnapshot[] | null;
    "usageCostAssociations": UsageCostAssociationSnapshot[] | null;
    "usageLimitAssociations": UsageLimitAssociationSnapshot[] | null;
    "usageCostSourceCompleteness": UsageCostSourceCompletenessSnapshot[] | null;
    "hubSwitches": HubSwitchSnapshot[] | null;
}

export interface LogicalAccountSnapshot {
    "id": string;
    "serviceId": string;
    "displayName": string;
    "archivedAt": string;
    "createdAt": string;
    "updatedAt": string;
}

export interface OverviewCapacitySnapshot {
    "databaseSizeBytes": number;
    "rawSnapshotCount": number;
    "oldestSnapshotAt": string;
    "latestSnapshotAt": string;
}

export interface OverviewChecklistItemSnapshot {
    "step": number;
    "title": string;
    "status": StatusPresentationSnapshot;
    "route": string;
    "actionable": boolean;
}

export interface OverviewEstimationSummarySnapshot {
    "states": OverviewStatusCountSnapshot[] | null;
}

export interface OverviewFreshnessSnapshot {
    "status": StatusPresentationSnapshot;
    "reason": string;
    "observationAt": string;
    "ageLabel": string;
}

export interface OverviewHubSnapshot {
    "id": string;
    "displayName": string;
    "enabled": boolean;
    "collectionEnabled": boolean;
    "connection": StatusPresentationSnapshot;
    "currentCollection": StatusPresentationSnapshot;
    "lastCollection": StatusPresentationSnapshot;
    "lastCollectionAt": string;
    "lastSuccessAt": string;
    "lastFailureAt": string;
    "lastSkippedAt": string;
}

export interface OverviewHubSummarySnapshot {
    "totalCount": number;
    "enabledCount": number;
    "scheduledCount": number;
    "runningCount": number;
    "abnormalCount": number;
    "credentialReadyCount": number;
    "lastSuccessAt": string;
    "connectionStates": OverviewStatusCountSnapshot[] | null;
    "currentCollectionStates": OverviewStatusCountSnapshot[] | null;
    "lastCollectionStates": OverviewStatusCountSnapshot[] | null;
    "items": OverviewHubSnapshot[] | null;
}

export interface OverviewKindCountSnapshot {
    "code": string;
    "label": string;
    "count": number;
}

export interface OverviewMaintenanceSnapshot {
    "operation": string;
    "phase": string;
    "status": StatusPresentationSnapshot;
}

export interface OverviewRecentLimitSnapshot {
    "logicalAccountId": string;
    "limitDefinitionId": string;
    "serviceName": string;
    "accountName": string;
    "limitName": string;
    "cycleType": string;
    "remainingPercent": number | null;
    "remainingLabel": string;
    "remainingDetailLabel": string;
    "remaining": StatusPresentationSnapshot;
    "estimatedUsageLabel": string;
    "estimatedLimitLabel": string;
    "resetAt": string;
    "reset": StatusPresentationSnapshot;
    "lastIncrease": OverviewTimeSnapshot;
    "freshness": OverviewFreshnessSnapshot;
    "observationOnly": boolean;
    "privacyMasked": boolean;
    "accessibleLabel": string;
    "tooltip": string;
}

export interface OverviewRecoveryNoticeSnapshot {
    "status": StatusPresentationSnapshot;
    "artifactSha256": string;
}

export interface OverviewReviewSummarySnapshot {
    "actionItems": OverviewStatusCountSnapshot;
    "warnings": OverviewStatusCountSnapshot;
    "recalculationFailures": OverviewStatusCountSnapshot;
    "actionKinds": OverviewKindCountSnapshot[] | null;
    "warningKinds": OverviewKindCountSnapshot[] | null;
}

export interface OverviewSnapshot {
    "generatedAt": string;
    "timezoneConfirmed": boolean;
    "recoveryNotice": OverviewRecoveryNoticeSnapshot | null;
    "checklist": OverviewChecklistItemSnapshot[] | null;
    "hubs": OverviewHubSummarySnapshot;
    "review": OverviewReviewSummarySnapshot;
    "estimation": OverviewEstimationSummarySnapshot;
    "capacity": OverviewCapacitySnapshot;
    "recentLimits": OverviewRecentLimitSnapshot[] | null;
    "maintenance": OverviewMaintenanceSnapshot | null;
}

export interface OverviewStatusCountSnapshot {
    "status": StatusPresentationSnapshot;
    "count": number;
}

export interface OverviewTimeSnapshot {
    "occurredAt": string;
    "ageLabel": string;
}

export interface PlanHistorySnapshot {
    "id": string;
    "logicalAccountId": string;
    "planVersionId": string;
    "validFrom": string;
    "validTo": string;
    "createdAt": string;
    "updatedAt": string;
}

export interface PlanInput {
    "id": string;
    "serviceId": string;
    "name": string;
    "isBaseline": boolean;
}

export interface PlanLimitRuleInput {
    "id": string;
    "planVersionId": string;
    "limitDefinitionId": string;
    "limit": number | null;
    "multiplier": number | null;
    "officialSourceUrl": string;
}

export interface PlanLimitRuleSnapshot {
    "id": string;
    "planVersionId": string;
    "limitDefinitionId": string;
    "limit": number | null;
    "multiplier": number | null;
    "officialSourceUrl": string;
    "createdAt": string;
}

export interface PlanSnapshot {
    "id": string;
    "serviceId": string;
    "name": string;
    "isBaseline": boolean;
    "archivedAt": string;
    "createdAt": string;
    "updatedAt": string;
}

export interface PlanVersionInput {
    "id": string;
    "planId": string;
    "name": string;
    "validFrom": string;
    "validTo": string;
    "officialSourceUrl": string;
}

export interface PlanVersionSnapshot {
    "id": string;
    "planId": string;
    "name": string;
    "validFrom": string;
    "validTo": string;
    "officialSourceUrl": string;
    "createdAt": string;
}

export interface RawSnapshotDetail {
    "snapshotId": string;
    "attemptId": string;
    "hubId": string;
    "responseKind": string;
    "receivedStartedAt": string;
    "receivedCompletedAt": string;
    "httpStatus": number;
    "apiContract": string;

    /**
     * Body is the redacted display text, never the persisted raw bytes.
     */
    "body": string;
}

export interface RawSnapshotSnapshot {
    "snapshotId": string;
    "attemptId": string;
    "hubId": string;
    "responseKind": string;
    "receivedStartedAt": string;
    "receivedCompletedAt": string;
    "httpStatus": number;
    "apiContract": string;
}

export interface ReviewCurrentAssociationSnapshot {
    "logicalAccountDisplayName": string;
    "limitMeaning": string;
    "planVersionName": string;
    "associationValidFrom": string;
    "associationValidTo": string;
    "planValidFrom": string;
    "planValidTo": string;
}

export interface ReviewFilterInput {
    "cursor": string;
    "limit": number;
    "from": string;
    "to": string;
    "kind": string;
    "state": string;
    "impact": string;
    "hubId": string;
}

export interface ReviewItemSnapshot {
    "id": string;
    "kind": string;
    "state": string;
    "impact": string;
    "hubId": string;
    "sourceId": string;
    "targetId": string;
    "target": string;
    "rawLimitServiceIdentifier": string;
    "rawReportedPlanName": string;
    "accountKey": string;
    "accountDisplayName": string;
    "workspaceName": string;
    "deviceName": string;
    "firstObservedAt": string;
    "lastObservedAt": string;
    "targetPeriodStart": string;
    "targetPeriodEnd": string;
    "count": number;
    "evidenceIds": string[] | null;
    "estimationExclusionReason": string;
    "currentAssociation": ReviewCurrentAssociationSnapshot | null;
}

export interface ReviewPage {
    "items": ReviewItemSnapshot[] | null;
    "nextCursor": string;
    "hasMore": boolean;
}

export interface SaveSettingsInput {
    "theme": string;
    "displayTimeZone": string;
}

export interface ServiceIdentifierMappingInput {
    "id": string;
    "kind": string;
    "rawIdentifier": string;
    "serviceId": string;
    "validFrom": string;
    "validTo": string;
}

export interface ServiceIdentifierMappingSnapshot {
    "id": string;
    "kind": string;
    "rawIdentifier": string;
    "serviceId": string;
    "validFrom": string;
    "validTo": string;
    "createdAt": string;
}

export interface ServiceSnapshot {
    "id": string;
    "provider": string;
    "name": string;
    "officialKey": string;
    "archivedAt": string;
    "createdAt": string;
    "updatedAt": string;
}

export interface SettingsSnapshot {
    "theme": string;
    "displayTimeZone": string;
    "ianaTimeZones": string[] | null;
    "timezoneConfirmed": boolean;
    "systemDark": boolean;
}

export interface SplitLogicalAccountInput {
    "sourceId": string;
    "serviceId": string;
    "displayName": string;
    "candidateIds": string[] | null;
}

export interface StandardPriceInput {
    "id": string;
    "planVersionId": string;
    "usdMonthlyPerSeat": number;
    "sourceUrl": string;
    "validFrom": string;
    "validTo": string;
}

export interface StandardPriceSnapshot {
    "id": string;
    "planVersionId": string;
    "usdMonthlyPerSeat": number;
    "sourceUrl": string;
    "validFrom": string;
    "validTo": string;
    "createdAt": string;
}

/**
 * StatusPresentationSnapshot is the single display contract for status text,
 * Fluent intent, icon, explanation and next action used by M01 and T01.
 */
export interface StatusPresentationSnapshot {
    "code": string;
    "label": string;
    "intent": string;
    "icon": string;
    "description": string;
    "nextAction": string;
    "nextRoute": string;
}

export interface UpdateHubInput {
    "id": string;
    "displayName": string;
    "url": string;
    "collectionIntervalSeconds": number;
}

export interface UpdateLogicalAccountInput {
    "id": string;
    "serviceId": string;
    "displayName": string;
}

export interface UpdatePlanHistoryInput {
    "id": string;
    "logicalAccountId": string;
    "planVersionId": string;
    "validFrom": string;
    "validTo": string;
}

export interface UpdateServiceInput {
    "id": string;
    "provider": string;
    "name": string;
    "officialKey": string;
    "archived": boolean;
}

export interface UsageBreakdownSnapshot {
    "key": string;
    "categoryKey": string;
    "label": string;
    "attribution": string;
    "tokens": number;
    "apiCostUsd": number;
    "apiCostUsdText": string;
    "observationCount": number;
    "evidenceRoute": string;
}

export interface UsageCostAssociationInput {
    "id": string;
    "usageCostSourceId": string;
    "logicalAccountId": string;
    "validFrom": string;
    "validTo": string;
}

export interface UsageCostAssociationSnapshot {
    "id": string;
    "usageCostSourceId": string;
    "logicalAccountId": string;
    "validFrom": string;
    "validTo": string;
    "createdAt": string;
    "updatedAt": string;
}

export interface UsageCostSourceCompletenessInput {
    "id": string;
    "usageCostSourceId": string;
    "validFrom": string;
    "validTo": string;
    "state": string;
    "logicalAccountIds": string[] | null;
    "excludedActivity": string[] | null;
}

export interface UsageCostSourceCompletenessSnapshot {
    "id": string;
    "usageCostSourceId": string;
    "validFrom": string;
    "validTo": string;
    "state": string;
    "logicalAccountIds": string[] | null;
    "excludedActivity": string[] | null;
    "createdAt": string;
    "updatedAt": string;
}

export interface UsageCostSourceSnapshot {
    "id": string;
    "hubId": string;
    "deviceId": string;
    "rawServiceIdentifier": string;
    "createdAt": string;
}

export interface UsageEvidenceSnapshot {
    "sourceId": string;
    "startObservationId": string;
    "endObservationId": string;
    "startSnapshotId": string;
    "endSnapshotId": string;
    "hubName": string;
    "collectionDeviceId": string;
    "deviceId": string;
    "rawServiceIdentifier": string;
    "startAt": string;
    "endAt": string;
    "jsonPath": string;
    "m08Route": string;
}

export interface UsageExportSnapshot {
    "filename": string;
    "mimeType": string;
    "content": string;
}

export interface UsageFilterInput {
    "from": string;
    "to": string;
    "displayTimeZone": string;
    "granularity": string;
    "groupBy": string;
    "hubId": string;
    "collectionDeviceId": string;
    "deviceId": string;
    "serviceId": string;
    "rawServiceIdentifier": string;
    "logicalAccountId": string;
    "planVersionId": string;
    "limitDefinitionId": string;
    "model": string;
}

export interface UsageLimitAssociationInput {
    "id": string;
    "usageLimitSourceId": string;
    "logicalAccountId": string;
    "limitDefinitionId": string;
    "validFrom": string;
    "validTo": string;
}

export interface UsageLimitAssociationSnapshot {
    "id": string;
    "usageLimitSourceId": string;
    "logicalAccountId": string;
    "limitDefinitionId": string;
    "validFrom": string;
    "validTo": string;
    "createdAt": string;
    "updatedAt": string;
}

export interface UsageLimitSourceSnapshot {
    "id": string;
    "hubId": string;
    "deviceId": string;
    "accountKey": string;
    "rawServiceIdentifier": string;
    "windowKey": string;
    "normalizedKind": string;
    "normalizedMetric": string;
    "normalizedLabel": string;
    "createdAt": string;
}

export interface UsageNativeAmountSnapshot {
    "observationId": string;
    "hubName": string;
    "deviceId": string;
    "serviceIdentifier": string;
    "label": string;
    "metric": string;
    "used": string;
    "limit": string;
    "remaining": string;
    "currency": string;
    "observedAt": string;
    "m08Route": string;
}

export interface UsagePointSnapshot {
    "periodStart": string;
    "periodEnd": string;
    "tokens": number;
    "sharedTokens": number;
    "apiCostUsd": number;
    "sharedApiCostUsd": number;
    "apiCostUsdText": string;
    "sharedApiCostUsdText": string;
    "observationCount": number;
    "breakdown": UsageBreakdownSnapshot[] | null;
}

export interface UsageSnapshot {
    "generatedAt": string;
    "from": string;
    "to": string;
    "displayTimeZone": string;
    "granularity": string;
    "groupBy": string;
    "summary": UsageSummarySnapshot;
    "series": UsagePointSnapshot[] | null;
    "breakdown": UsageBreakdownSnapshot[] | null;
    "nativeAmounts": UsageNativeAmountSnapshot[] | null;
    "evidence": UsageEvidenceSnapshot[] | null;
    "unallocatedObservationCount": number;
    "unallocatedTokens": number;
    "unallocatedApiCostUsd": number;
    "unallocatedApiCostUsdText": string;
}

export interface UsageSummarySnapshot {
    "tokens": number;
    "sharedTokens": number;
    "apiCostUsd": number;
    "sharedApiCostUsd": number;
    "apiCostUsdText": string;
    "sharedApiCostUsdText": string;
    "sourceCount": number;
    "observationCount": number;
}
