// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface CreateHubInput {
    "displayName": string;
    "url": string;
    "collectionIntervalSeconds": number;
    "collectionEnabled": boolean;
    "secret": string;
}

export interface HubSnapshot {
    "id": string;
    "displayName": string;
    "url": string;
    "collectionEnabled": boolean;
    "collectionIntervalSeconds": number;
    "apiContract": string;
    "credentialState": string;
    "credentialReady": boolean;
    "connectionState": string;
    "connectionCheckedAt": string;
    "connectionFailureNote": string;
}

export interface SaveSettingsInput {
    "theme": string;
    "displayTimeZone": string;
}

export interface SettingsSnapshot {
    "theme": string;
    "displayTimeZone": string;
    "ianaTimeZones": string[] | null;
    "systemDark": boolean;
}

export interface UpdateHubInput {
    "id": string;
    "displayName": string;
    "url": string;
    "collectionIntervalSeconds": number;
}
