// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetOverview returns display-ready domain decisions. In privacy mode the raw
 * sensitive values never cross the Go/Wails boundary.
 */
export function GetOverview(privacyMode: boolean): $CancellablePromise<$models.OverviewSnapshot> {
    return $Call.ByID(2507200482, privacyMode);
}
