// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ReviewService is the read-only Wails boundary for M04. It exposes
 * navigation identifiers and non-secret evidence only; raw snapshots and
 * credentials never cross this boundary.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function GetReviewItems(input: $models.ReviewFilterInput): $CancellablePromise<$models.ReviewPage> {
    return $Call.ByID(2979103508, input);
}
