// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function GetSettings(): $CancellablePromise<$models.SettingsSnapshot> {
    return $Call.ByID(2205987454);
}

export function SaveSettings(input: $models.SaveSettingsInput): $CancellablePromise<$models.SettingsSnapshot> {
    return $Call.ByID(4046292377, input);
}
