// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function ExportUsage(input: $models.UsageFilterInput, format: string): $CancellablePromise<$models.UsageExportSnapshot> {
    return $Call.ByID(1420066594, input, format);
}

export function GetCalendarPeriodUsage(input: $models.CalendarPeriodUsageInput): $CancellablePromise<$models.CalendarPeriodUsageSnapshot> {
    return $Call.ByID(4250982811, input);
}

export function GetUsage(input: $models.UsageFilterInput): $CancellablePromise<$models.UsageSnapshot> {
    return $Call.ByID(1220379014, input);
}
