// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

export function ConfirmCloseMain(): $CancellablePromise<void> {
    return $Call.ByID(3231058385);
}

export function ConfirmQuit(): $CancellablePromise<void> {
    return $Call.ByID(1226050351);
}

export function OpenMain(): $CancellablePromise<void> {
    return $Call.ByID(1960628325);
}

/**
 * SetCompactExpanded changes the T01 width while retaining its saved placement.
 * The saved width is also the persisted expanded state.
 */
export function SetCompactExpanded(expanded: boolean): $CancellablePromise<void> {
    return $Call.ByID(3180832488, expanded);
}

export function SetMainDirty(dirty: boolean): $CancellablePromise<void> {
    return $Call.ByID(2933188419, dirty);
}
