// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as analytics$0 from "../analytics/models.js";

export interface Dashboard {
    "periodKey": string;
    "totalTokens": number;
    "totalCostUsd": number;
    "subscriptions": SubscriptionMetric[] | null;
    "trend": analytics$0.Observation[] | null;
    "breakdowns": analytics$0.UsageBreakdown[] | null;
}

export interface FetchResult {
    "snapshotId": number;
    "observationCount": number;
    "fetchedAt": string;
    "message": string;
}

export interface Settings {
    "hubUrl": string;
    "secret"?: string;
    "secretConfigured": boolean;
    "intervalSeconds": number;
}

export interface Status {
    "configured": boolean;
    "running": boolean;
    "lastError": string;
    "lastFetchedAt": string;
    "snapshotCount": number;
    "intervalSeconds": number;
}

export interface SubscriptionInput {
    "provider": string;
    "accountKey": string;
    "accountLabel": string;
    "planName": string;
    "monthlyPriceUsd": number;
}

export interface SubscriptionMetric {
    "id": number;
    "provider": string;
    "accountKey": string;
    "accountLabel": string;
    "planName": string;
    "monthlyPriceUsd": number;
    "actualUsageUsd": number | null;
    "estimatedLimitUsd": number | null;
    "actualValueMultiplier": number | null;
    "estimatedMaxValueMultiplier": number | null;
    "dataQuality": string;
}
