// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface FetchResult {
    "snapshotId": number;
    "observationCount": number;
    "fetchedAt": string;
    "message": string;
}

export interface Settings {
    "hubUrl": string;
    "secret"?: string;
    "secretConfigured": boolean;
    "intervalSeconds": number;
}

export interface Status {
    "configured": boolean;
    "running": boolean;
    "lastError": string;
    "lastFetchedAt": string;
    "snapshotCount": number;
    "intervalSeconds": number;
}
