// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as analytics$0 from "../analytics/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function FetchNow(): $CancellablePromise<$models.FetchResult> {
    return $Call.ByID(788538493);
}

export function GetHistory(limit: number): $CancellablePromise<analytics$0.Observation[] | null> {
    return $Call.ByID(3808097177, limit);
}

export function GetSettings(): $CancellablePromise<$models.Settings> {
    return $Call.ByID(3455856506);
}

export function GetStatus(): $CancellablePromise<$models.Status> {
    return $Call.ByID(476699857);
}

export function SaveSettings(settings: $models.Settings): $CancellablePromise<void> {
    return $Call.ByID(73086565, settings);
}

export function Start(): $CancellablePromise<void> {
    return $Call.ByID(1225697199);
}

export function Stop(): $CancellablePromise<void> {
    return $Call.ByID(2217185525);
}
