import { cpSync, mkdirSync, readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { root } from './lib.mjs';
const target = join(root, 'release/app');
if (existsSync(target))
    throw new Error('release/app が既にあります。内容を確認し別名へ移動してから実行してください。');
const lock = readFileSync(join(root, 'package-lock.json'));
mkdirSync(target, { recursive: true });
cpSync(join(root, 'dist'), join(target, 'dist'), { recursive: true });
mkdirSync(join(target, 'frontend'), { recursive: true });
cpSync(join(root, 'frontend/dist'), join(target, 'frontend/dist'), { recursive: true });
const pkg = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'));
pkg.scripts = { start: 'node --env-file-if-exists=.env dist/backend/main.js' };
writeFileSync(join(target, 'package.json'), JSON.stringify(pkg, null, 2) + '\n');
writeFileSync(join(target, 'package-lock.json'), lock);
cpSync(join(root, '.env.example'), join(target, '.env.example'));
cpSync(join(root, '.nvmrc'), join(target, '.nvmrc'));
mkdirSync(join(target, 'config'), { recursive: true });
cpSync(join(root, 'config/hubs.example.json'), join(target, 'config/hubs.example.json'));
console.log('release/app を配備し、.nvmrcの指定版Node.jsを選択、npm ci --omit=dev、.envとHub接続設定、npm start の順に実行してください。dataは配備領域の外へ置いてください。');
