import {
  createFakeBackend,
  emptyDataManagementState,
  emptyOverviewSnapshot,
  type AuditRecord,
  type CatalogSnapshot,
  type DataManagementStateSnapshot,
  type HubSnapshot,
  type LimitObservationSnapshot,
  type LimitSeriesSnapshot,
  type OverviewSnapshot,
  type ReviewItemSnapshot,
} from "./backend";
import type { StatusPresentationSnapshot } from "../../bindings/token-monitor-analytics/internal/desktop/models.js";

const now = "2026-08-26T00:10:00Z";

function status(
  code: string,
  label: string,
  intent = "informative",
  icon = "info",
): StatusPresentationSnapshot {
  return {
    code,
    label,
    intent,
    icon,
    description: `${label}です。`,
    nextAction: "",
    nextRoute: "",
  };
}

const hub: HubSnapshot = {
  id: "hub-evaluation",
  displayName: "評価 Hub（192.168.0.16）",
  url: "http://192.168.0.16:17321",
  enabled: true,
  collectionEnabled: true,
  collectionIntervalSeconds: 300,
  apiContract: "schema=1; runtime=node-hub; usageUpdatedAt=true",
  credentialState: "registered",
  credentialReady: true,
  connectionState: "connected",
  connectionCheckedAt: "2026-08-26T00:05:00Z",
  connectionFailureNote: "",
};

const currentStatsBody = JSON.stringify(
  {
    devices: [
      {
        deviceId: "device-evaluation",
        usage: {
          providers: [
            {
              rawServiceIdentifier: "codex",
              usageUpdatedAt: "2026-08-26T00:05:00Z",
              costUsd: "31.365",
            },
          ],
        },
        limits: {
          providers: [
            {
              rawServiceIdentifier: "codex",
              providerUpdatedAt: "2026-08-26T00:05:00Z",
              accountKey: "account-key",
              planLabel: "Plus",
              windows: [
                {
                  windowKey: "weekly-percent",
                  normalizedKind: "weekly",
                  usedPercent: 25.5,
                  remainingPercent: 74.5,
                  resetsAt: "2026-09-01T00:00:00Z",
                },
              ],
            },
            {
              rawServiceIdentifier: "claude",
              providerUpdatedAt: "2026-08-26T00:05:00Z",
              planLabel: "Pro",
              windows: [
                {
                  windowKey: "five-hour-percent",
                  normalizedKind: "five_hour",
                  usedPercent: 58,
                  remainingPercent: 42,
                  resetsAt: "2026-08-26T05:00:00Z",
                },
              ],
            },
          ],
        },
        secret: "[MASKED]",
      },
    ],
  },
  null,
  2,
);

const startStatsBody = JSON.stringify(
  {
    devices: [
      {
        deviceId: "device-evaluation",
        usage: {
          providers: [
            {
              rawServiceIdentifier: "codex",
              usageUpdatedAt: "2026-08-25T00:05:00Z",
              costUsd: "0.000",
            },
          ],
        },
        limits: {
          providers: [
            {
              rawServiceIdentifier: "codex",
              providerUpdatedAt: "2026-08-25T00:05:00Z",
              accountKey: "account-key",
              planLabel: "Plus",
              windows: [
                {
                  windowKey: "weekly-percent",
                  normalizedKind: "weekly",
                  usedPercent: 0,
                  remainingPercent: 100,
                  resetsAt: "2026-09-01T00:00:00Z",
                },
              ],
            },
          ],
        },
        secret: "[MASKED]",
      },
    ],
  },
  null,
  2,
);

const overview: OverviewSnapshot = {
  ...emptyOverviewSnapshot,
  generatedAt: now,
  timezoneConfirmed: true,
  checklist: [
    {
      step: 1,
      title: "表示タイムゾーンを確認",
      status: status("complete", "完了", "success", "checkmark"),
      route: "/settings",
      actionable: false,
    },
    {
      step: 2,
      title: "Hub と資格情報を登録",
      status: status("complete", "完了", "success", "checkmark"),
      route: "/hubs",
      actionable: false,
    },
  ],
  hubs: {
    ...emptyOverviewSnapshot.hubs,
    totalCount: 1,
    enabledCount: 1,
    scheduledCount: 1,
    credentialReadyCount: 1,
    lastSuccessAt: "2026-08-26T00:05:00Z",
    connectionStates: [
      {
        status: status("connected", "接続済み", "success", "checkmark"),
        count: 1,
      },
    ],
    currentCollectionStates: [
      { status: status("collection_idle", "待機中"), count: 1 },
    ],
    lastCollectionStates: [
      {
        status: status(
          "collection_succeeded",
          "取得成功",
          "success",
          "checkmark",
        ),
        count: 1,
      },
    ],
    items: [
      {
        id: hub.id,
        displayName: hub.displayName,
        enabled: true,
        collectionEnabled: true,
        connection: status("connected", "接続済み", "success", "checkmark"),
        currentCollection: status("collection_idle", "待機中"),
        lastCollection: status(
          "collection_succeeded",
          "取得成功",
          "success",
          "checkmark",
        ),
        lastCollectionAt: "2026-08-26T00:05:00Z",
        lastSuccessAt: "2026-08-26T00:05:00Z",
        lastFailureAt: "",
        lastSkippedAt: "",
      },
    ],
  },
  review: {
    ...emptyOverviewSnapshot.review,
    actionItems: {
      ...emptyOverviewSnapshot.review.actionItems,
      count: 1,
    },
    warnings: { ...emptyOverviewSnapshot.review.warnings, count: 1 },
    actionKinds: [
      { code: "identification_candidate", label: "サービス同定候補", count: 1 },
    ],
    warningKinds: [
      {
        code: "missing_account_key",
        label: "アカウント識別情報なし",
        count: 1,
      },
    ],
  },
  estimation: {
    states: [
      {
        status: status("provisional", "暫定推定", "informative", "info"),
        count: 1,
      },
    ],
  },
  capacity: {
    databaseSizeBytes: 12_582_912,
    rawSnapshotCount: 24,
    oldestSnapshotAt: "2026-08-25T00:00:00Z",
    latestSnapshotAt: "2026-08-26T00:05:00Z",
  },
  recentLimits: [
    {
      logicalAccountId: "account-codex",
      limitDefinitionId: "limit-weekly",
      serviceName: "Codex",
      accountName: "個人アカウント",
      limitName: "週次利用枠",
      cycleType: "weekly",
      remainingPercent: 74.5,
      remainingLabel: "74.5%",
      remainingDetailLabel: "74.50%",
      remaining: status("remaining_high", "残量良好", "success", "checkmark"),
      resetAt: "2026-09-01T00:00:00Z",
      reset: status("reset_scheduled", "リセット予定"),
      lastIncrease: { occurredAt: "2026-08-26T00:00:00Z", ageLabel: "10分前" },
      freshness: {
        status: status("freshness_current", "最新", "success", "checkmark"),
        reason: "最新の取得に含まれています。",
        observationAt: "2026-08-26T00:05:00Z",
        ageLabel: "5分前",
      },
      privacyMasked: false,
      accessibleLabel: "Codex、個人アカウント、残り 74.5%",
      tooltip: "週次利用枠、残り 74.5%",
    },
  ],
};

const privacyOverview: OverviewSnapshot = {
  ...overview,
  recentLimits: (overview.recentLimits ?? []).map((item) => {
    const hidden = status("privacy_hidden", "非表示", "subtle");
    return {
      ...item,
      accountName: "••••",
      remainingPercent: null,
      remainingLabel: "••••",
      remainingDetailLabel: "••••",
      remaining: hidden,
      resetAt: "",
      reset: hidden,
      privacyMasked: true,
      accessibleLabel: `${item.serviceName}、••••、${item.limitName}、残り ••••、非表示、利用増加 ${item.lastIncrease.ageLabel}、最新観測 ${item.freshness.ageLabel}`,
      tooltip: `残り ••••・利用増加 ${item.lastIncrease.ageLabel}（UTC ${item.lastIncrease.occurredAt}）・最新観測 ${item.freshness.ageLabel}（UTC ${item.freshness.observationAt}）`,
    };
  }),
};

const limitSeries: LimitSeriesSnapshot = {
  id: "series-codex-weekly",
  serviceId: "service-codex",
  serviceName: "Codex",
  logicalAccountId: "account-codex",
  logicalAccountName: "個人アカウント",
  limitDefinitionId: "limit-weekly",
  limitDefinitionName: "週次利用枠",
  cycleType: "weekly",
  usageLimitSourceId: "source-weekly",
  associationId: "association-weekly",
  normalizedKind: "weekly",
  normalizedMetric: "percent",
  planHistoryId: "plan-history-plus",
  planVersionId: "plan-plus-2026",
  planVersionName: "Plus 2026",
  planLimitRuleId: "rule-plus-weekly",
  planLimit: 1000,
  planLimitLabel: "1,000.00",
  multiplier: null,
  usedPercent: 25.5,
  usedPercentLabel: "25.5",
  usedPercentDetailLabel: "25.50",
  remainingPercent: 74.5,
  remainingLabel: "74.5%",
  remainingDetailLabel: "74.50%",
  resetAt: "2026-09-01T00:00:00Z",
  latestObservationAt: "2026-08-26T00:05:00Z",
  seriesState: "normal",
  state: status("provisional", "暫定推定", "informative", "info"),
  stateReasonCode: "exactly_identified",
  stateReason: "利用枠観測から暫定値を算出しました。",
  currentInterval: {
    id: "interval-codex-weekly-current",
    serviceId: "service-codex",
    logicalAccountId: "account-codex",
    usageLimitSourceId: "source-weekly",
    limitDefinitionId: "limit-weekly",
    planVersionId: "plan-plus-2026",
    cycleType: "weekly",
    validFrom: "2026-08-25T00:00:00Z",
    validTo: "2026-09-01T00:00:00Z",
    state: "estimable",
    stateLabel: "推定可能",
    exclusionReasonCode: "",
    exclusionReason: "",
    boundaryIds: ["boundary-weekly-start", "boundary-weekly-end"],
    boundaries: [
      {
        id: "boundary-weekly-start",
        kindCode: "limit_reset",
        kind: "利用枠リセット",
        at: "2026-08-25T00:00:00Z",
        reason: "週次利用枠の開始を観測しました。",
        relatedId: "observation-weekly-start",
      },
      {
        id: "boundary-weekly-end",
        kindCode: "scheduled_reset",
        kind: "次回リセット",
        at: "2026-09-01T00:00:00Z",
        reason: "観測されたリセット予定時刻です。",
        relatedId: "observation-weekly",
      },
    ],
    role: "current",
    roleLabel: "カレント",
  },
  result: {
    id: "result-codex-weekly",
    resultSetKey: "codex-weekly-2026-08-25",
    status: status("provisional", "暫定推定", "informative", "info"),
    statusReasonCode: "exactly_identified",
    statusReason: "2つの観測点と利用額差分から一意に推定しました。",
    limits: [123],
    observationPointCount: 2,
    differenceRowCount: 1,
    rank: 1,
    absoluteErrorRatio: 0,
    absoluteErrorRatioLabel: "0.00%",
    maxTimeDelta: "1秒",
    calculationLogicVersion: "limit-estimation-v1",
    matchingRuleVersion: "nearest-observation-v1",
    inputFingerprint: "showcase-codex-weekly-v1",
    calculationIntervalIds: ["interval-codex-weekly-current"],
    validFrom: "2026-08-25T00:00:00Z",
    validTo: "2026-09-01T00:00:00Z",
    differenceRows: [
      {
        id: "difference-codex-weekly",
        startPointId: "point-weekly-start",
        endPointId: "point-weekly-current",
        startAt: "2026-08-25T00:05:00Z",
        endAt: "2026-08-26T00:05:00Z",
        coefficients: [0.255],
        cost: 31.365,
        accepted: true,
        exclusionReasonCode: "",
        exclusionReason: "",
      },
    ],
    evidence: [
      {
        id: "evidence-weekly-start",
        kind: "matched_observation",
        pointId: "point-weekly-start",
        sourceId: "source-weekly",
        observationId: "observation-weekly-start",
        snapshotId: "stats-snapshot-01",
        associationId: "association-weekly",
        completenessId: "completeness-codex",
        planHistoryId: "plan-history-plus",
        logicalAccountId: "account-codex",
        planVersionId: "plan-plus-2026",
        observedAt: "2026-08-25T00:05:00Z",
        timeDelta: "0秒",
        normalizationGeneration: 1,
        normalizationRuleVersion: "api-stats-v1",
        normalizationLogicVersion: "t012-normalize-v1",
        detailsJson: '{"remainingPercent":100,"costUsd":"0.000"}',
        m08Route: "/evidence?observationId=observation-weekly-start",
      },
      {
        id: "evidence-weekly-current",
        kind: "matched_observation",
        pointId: "point-weekly-current",
        sourceId: "source-weekly",
        observationId: "observation-weekly",
        snapshotId: "stats-snapshot-24",
        associationId: "association-weekly",
        completenessId: "completeness-codex",
        planHistoryId: "plan-history-plus",
        logicalAccountId: "account-codex",
        planVersionId: "plan-plus-2026",
        observedAt: "2026-08-26T00:05:00Z",
        timeDelta: "1秒",
        normalizationGeneration: 1,
        normalizationRuleVersion: "api-stats-v1",
        normalizationLogicVersion: "t012-normalize-v1",
        detailsJson: '{"remainingPercent":74.5,"costUsd":"31.365"}',
        m08Route: "/evidence?observationId=observation-weekly",
      },
    ],
  },
  latestValidReference: null,
  estimatedLimit: 123,
  estimatedLimitLabel: "123.00 USD相当",
};

const reviewItem: ReviewItemSnapshot = {
  id: "review-claude-identification",
  kind: "identification_candidate",
  state: "unconfirmed",
  impact: "current_calculation_impact",
  hubId: hub.id,
  sourceId: "source-unassigned",
  targetId: "candidate-claude",
  target: "Claude / Pro",
  rawLimitServiceIdentifier: "claude",
  rawReportedPlanName: "Pro",
  accountKey: "",
  accountDisplayName: "作業アカウント",
  workspaceName: "Engineering",
  deviceName: "評価端末",
  firstObservedAt: "2026-08-25T00:00:00Z",
  lastObservedAt: "2026-08-26T00:05:00Z",
  targetPeriodStart: "2026-08-25T00:00:00Z",
  targetPeriodEnd: "2026-09-01T00:00:00Z",
  count: 2,
  evidenceIds: ["observation-unassigned"],
  estimationExclusionReason:
    "サービスとプランの同定が未確認のため推定対象へ関連付けていません。",
  currentAssociation: null,
};

const warningItem: ReviewItemSnapshot = {
  id: "review-missing-account-key",
  kind: "missing_account_key",
  state: "missing",
  impact: "calculation_interval_impossible",
  hubId: hub.id,
  sourceId: "source-unassigned",
  targetId: "observation-unassigned",
  target: "Claude / 5時間利用枠",
  rawLimitServiceIdentifier: "claude",
  rawReportedPlanName: "Pro",
  accountKey: "",
  accountDisplayName: "作業アカウント",
  workspaceName: "Engineering",
  deviceName: "評価端末",
  firstObservedAt: "2026-08-25T23:55:00Z",
  lastObservedAt: "2026-08-26T00:05:00Z",
  targetPeriodStart: "2026-08-25T23:55:00Z",
  targetPeriodEnd: "2026-08-26T05:00:00Z",
  count: 2,
  evidenceIds: ["observation-unassigned"],
  estimationExclusionReason:
    "アカウント識別情報がないため利用枠系列へ関連付けできません。",
  currentAssociation: null,
};

const audit: AuditRecord = {
  sequence: 12,
  auditId: "audit-hub-connected",
  occurredAt: "2026-08-26T00:05:00Z",
  actor: "user",
  action: "hub_connection_succeeded",
  entityType: "hub",
  entityId: hub.id,
  beforeJson: '{"connectionState":"not_checked"}',
  afterJson: '{"connectionState":"connected","credential":"[非表示]"}',
};

const dataManagementState: DataManagementStateSnapshot = {
  ...emptyDataManagementState,
  capacity: {
    status: "success",
    capacity: {
      databaseSizeBytes: 12_582_912,
      rawSnapshotCount: 24,
      oldestCompletedAt: "2026-08-25T00:00:00Z",
      latestCompletedAt: "2026-08-26T00:05:00Z",
      rawJsonBytes: 8_388_608,
    },
    error: null,
  },
  backup: {
    status: "success",
    cancelAllowed: false,
    artifact: {
      path: "D:\\Backups\\token-monitor-analytics-20260826.zip",
      artifactSha256:
        "d2d2a0c7a8ad71d45dfebcdfb8da39c16d6ed99d94c5897e58d6e3c2bf63213e",
      sizeBytes: 4_718_592,
      formatVersion: 1,
      schemaVersion: 13,
      appVersion: "0.1.0",
      createdAt: "2026-08-26T00:08:00Z",
      warning: "",
    },
    error: null,
  },
  restore: {
    validation: {
      status: "success",
      cancelAllowed: false,
      applyAllowed: true,
      operationId: "restore-validation-showcase",
      artifact: {
        path: "D:\\Backups\\token-monitor-analytics-20260826.zip",
        artifactSha256:
          "d2d2a0c7a8ad71d45dfebcdfb8da39c16d6ed99d94c5897e58d6e3c2bf63213e",
        sizeBytes: 4_718_592,
        formatVersion: 1,
        schemaVersion: 13,
        appVersion: "0.1.0",
        createdAt: "2026-08-26T00:08:00Z",
        warning: "",
      },
      error: null,
    },
    trial: {
      status: "passed",
      cancelAllowed: false,
      artifactSha256:
        "d2d2a0c7a8ad71d45dfebcdfb8da39c16d6ed99d94c5897e58d6e3c2bf63213e",
      testedAt: "2026-08-26T00:09:00Z",
      warning: "",
      error: null,
    },
    apply: emptyDataManagementState.restore.apply,
  },
};

const catalog: Partial<CatalogSnapshot> = {
  services: [
    {
      id: "service-codex",
      provider: "OpenAI",
      name: "Codex",
      officialKey: "openai.codex",
      archivedAt: "",
      createdAt: "2026-08-25T00:00:00Z",
      updatedAt: "2026-08-26T00:05:00Z",
    },
  ],
  serviceIdentifierMappings: [
    {
      id: "mapping-cost-codex",
      kind: "usage_cost",
      rawIdentifier: "codex",
      serviceId: "service-codex",
      validFrom: "2026-08-25T00:00:00Z",
      validTo: "",
      createdAt: "2026-08-25T00:00:00Z",
    },
    {
      id: "mapping-limit-codex",
      kind: "usage_limit",
      rawIdentifier: "codex",
      serviceId: "service-codex",
      validFrom: "2026-08-25T00:00:00Z",
      validTo: "",
      createdAt: "2026-08-25T00:00:00Z",
    },
  ],
  limitDefinitions: [
    {
      id: "limit-weekly",
      serviceId: "service-codex",
      cycleType: "weekly",
      meaning: "週次利用枠",
      unit: "%",
      billingConfirmation: "not_applicable",
      archivedAt: "",
      createdAt: "2026-08-25T00:00:00Z",
      updatedAt: "2026-08-26T00:05:00Z",
    },
  ],
  plans: [
    {
      id: "plan-plus",
      serviceId: "service-codex",
      name: "Plus",
      isBaseline: true,
      archivedAt: "",
      createdAt: "2026-08-25T00:00:00Z",
      updatedAt: "2026-08-26T00:05:00Z",
    },
  ],
  planVersions: [
    {
      id: "plan-plus-2026",
      planId: "plan-plus",
      name: "Plus 2026",
      validFrom: "2026-01-01T00:00:00Z",
      validTo: "",
      officialSourceUrl: "https://example.invalid/plans/plus",
      createdAt: "2026-08-25T00:00:00Z",
    },
  ],
  planLimitRules: [
    {
      id: "rule-plus-weekly",
      planVersionId: "plan-plus-2026",
      limitDefinitionId: "limit-weekly",
      limit: 1000,
      multiplier: null,
      officialSourceUrl: "https://example.invalid/plans/plus#weekly-limit",
      createdAt: "2026-08-25T00:00:00Z",
    },
  ],
  identificationCandidates: [
    {
      id: "candidate-codex",
      rawLimitServiceIdentifier: "codex",
      rawReportedPlanName: "Plus",
      state: "confirmed",
      serviceId: "service-codex",
      planId: "plan-plus",
      firstObservedAt: "2026-08-25T00:00:00Z",
      lastObservedAt: "2026-08-26T00:05:00Z",
      createdAt: "2026-08-25T00:00:00Z",
      updatedAt: "2026-08-26T00:05:00Z",
      observations: [
        {
          id: "candidate-observation-codex",
          candidateId: "candidate-codex",
          hubId: hub.id,
          hubAccountDisplay: "個人アカウント / Personal / 評価端末",
          observedAt: "2026-08-26T00:05:00Z",
        },
      ],
    },
    {
      id: "candidate-claude",
      rawLimitServiceIdentifier: "claude",
      rawReportedPlanName: "Pro",
      state: "unconfirmed",
      serviceId: "",
      planId: "",
      firstObservedAt: "2026-08-25T23:55:00Z",
      lastObservedAt: "2026-08-26T00:05:00Z",
      createdAt: "2026-08-25T23:55:00Z",
      updatedAt: "2026-08-26T00:05:00Z",
      observations: [
        {
          id: "candidate-observation-claude",
          candidateId: "candidate-claude",
          hubId: hub.id,
          hubAccountDisplay: "作業アカウント / Engineering / 評価端末",
          observedAt: "2026-08-26T00:05:00Z",
        },
      ],
    },
  ],
};

const limitObservation: LimitObservationSnapshot = {
  observationId: "observation-weekly",
  snapshotId: "stats-snapshot-24",
  hubId: hub.id,
  deviceId: "device-evaluation",
  rawServiceIdentifier: "codex",
  accountKey: "account-key",
  providerUpdatedAt: "2026-08-26T00:05:00Z",
  windowKey: "weekly-percent",
  normalizedKind: "weekly",
  normalizedMetric: "percent",
  normalizedLabel: "Weekly",
  planLabel: "Plus",
  usedPercent: 25.5,
  remainingPercent: 74.5,
  resetsAt: "2026-09-01T00:00:00Z",
  syncUploadIntervalMs: 300000,
  limitsRefreshMs: 300000,
  analyticsIntervalSeconds: 300,
  sourceTimezone: "Asia/Tokyo",
  sourceLocalDate: "2026-08-26",
  normalizationGeneration: 1,
  normalizationRuleVersion: "api-stats-v1",
  normalizationLogicVersion: "t012-normalize-v1",
  jsonPath: "$.devices[0].limits.providers[0].windows[0]",
  dedupeState: "canonical",
  dedupeKey: "evaluation-weekly",
  valueFingerprint: "25.5",
  windowKeyConflict: false,
};

const startLimitObservation: LimitObservationSnapshot = {
  ...limitObservation,
  observationId: "observation-weekly-start",
  snapshotId: "stats-snapshot-01",
  providerUpdatedAt: "2026-08-25T00:05:00Z",
  usedPercent: 0,
  remainingPercent: 100,
  sourceLocalDate: "2026-08-25",
  dedupeKey: "evaluation-weekly-start",
  valueFingerprint: "0",
};

const unassignedLimitObservation: LimitObservationSnapshot = {
  ...limitObservation,
  observationId: "observation-unassigned",
  rawServiceIdentifier: "claude",
  accountKey: "",
  windowKey: "five-hour-percent",
  normalizedKind: "five_hour",
  normalizedLabel: "5時間",
  planLabel: "Pro",
  usedPercent: 58,
  remainingPercent: 42,
  resetsAt: "2026-08-26T05:00:00Z",
  jsonPath: "$.devices[0].limits.providers[1].windows[0]",
  dedupeKey: "evaluation-five-hour-unassigned",
  valueFingerprint: "58",
};

export function createShowcaseBackend() {
  return createFakeBackend({
    canOpenMain: true,
    isShowcase: true,
    settings: { displayTimeZone: "Asia/Tokyo", timezoneConfirmed: true },
    overview,
    onGetOverview: (privacyMode) => (privacyMode ? privacyOverview : overview),
    hubs: [hub],
    limitSeries: [limitSeries],
    limitSeriesDetails: {
      [limitSeries.id]: {
        series: limitSeries,
        current: limitSeries.currentInterval,
        history: limitSeries.currentInterval
          ? [
              {
                ...limitSeries.currentInterval,
                id: "interval-codex-weekly-previous",
                validFrom: "2026-08-18T00:00:00Z",
                validTo: "2026-08-25T00:00:00Z",
                boundaryIds: ["boundary-weekly-previous"],
                boundaries: [
                  {
                    id: "boundary-weekly-previous",
                    kindCode: "limit_reset",
                    kind: "利用枠リセット",
                    at: "2026-08-18T00:00:00Z",
                    reason: "前回の週次利用枠の開始を観測しました。",
                    relatedId: "observation-weekly-start",
                  },
                ],
                role: "historical",
                roleLabel: "履歴",
              },
            ]
          : [],
      },
    },
    reviewItems: [reviewItem, warningItem],
    audits: [audit],
    dataManagementState,
    catalog,
    accounts: {
      hubAccountCandidates: [
        {
          id: "hub-account-codex",
          hubId: hub.id,
          serviceId: "service-codex",
          accountKey: "account-key",
          displayName: "個人アカウント",
          email: "sample@example.invalid",
          workspaceName: "Personal",
          deviceName: "評価端末",
          state: "associated",
          logicalAccountId: "account-codex",
          firstObservedAt: "2026-08-25T00:00:00Z",
          lastObservedAt: "2026-08-26T00:05:00Z",
          createdAt: "2026-08-25T00:00:00Z",
          updatedAt: "2026-08-26T00:05:00Z",
        },
      ],
      logicalAccounts: [
        {
          id: "account-codex",
          serviceId: "service-codex",
          displayName: "個人アカウント",
          archivedAt: "",
          createdAt: "2026-08-25T00:00:00Z",
          updatedAt: "2026-08-26T00:05:00Z",
        },
      ],
      planHistories: [
        {
          id: "plan-history-plus",
          logicalAccountId: "account-codex",
          planVersionId: "plan-plus-2026",
          validFrom: "2026-01-01T00:00:00Z",
          validTo: "",
          createdAt: "2026-08-25T00:00:00Z",
          updatedAt: "2026-08-26T00:05:00Z",
        },
      ],
    },
    linking: {
      usageCostSources: [
        {
          id: "cost-source-codex",
          hubId: hub.id,
          deviceId: "device-evaluation",
          rawServiceIdentifier: "codex",
          createdAt: "2026-08-25T00:00:00Z",
        },
      ],
      usageLimitSources: [
        {
          id: "source-weekly",
          hubId: hub.id,
          deviceId: "device-evaluation",
          accountKey: "account-key",
          rawServiceIdentifier: "codex",
          windowKey: "weekly-percent",
          normalizedKind: "weekly",
          normalizedMetric: "percent",
          normalizedLabel: "Weekly",
          createdAt: "2026-08-25T00:00:00Z",
        },
      ],
      usageCostAssociations: [
        {
          id: "cost-association-codex",
          usageCostSourceId: "cost-source-codex",
          logicalAccountId: "account-codex",
          validFrom: "2026-08-25T00:00:00Z",
          validTo: "",
          createdAt: "2026-08-25T00:00:00Z",
          updatedAt: "2026-08-26T00:05:00Z",
        },
      ],
      usageLimitAssociations: [
        {
          id: "association-weekly",
          usageLimitSourceId: "source-weekly",
          logicalAccountId: "account-codex",
          limitDefinitionId: "limit-weekly",
          validFrom: "2026-08-25T00:00:00Z",
          validTo: "",
          createdAt: "2026-08-25T00:00:00Z",
          updatedAt: "2026-08-26T00:05:00Z",
        },
      ],
      usageCostSourceCompleteness: [
        {
          id: "completeness-codex",
          usageCostSourceId: "cost-source-codex",
          validFrom: "2026-08-25T00:00:00Z",
          validTo: "",
          state: "confirmed",
          logicalAccountIds: ["account-codex"],
          excludedActivity: [],
          createdAt: "2026-08-25T00:00:00Z",
          updatedAt: "2026-08-26T00:05:00Z",
        },
      ],
      hubSwitches: [
        {
          id: "hub-switch-evaluation-device",
          oldHubId: hub.id,
          oldDeviceId: "device-evaluation-old",
          newHubId: hub.id,
          newDeviceId: "device-evaluation",
          collectionDeviceId: "device-evaluation",
          switchedAt: "2026-08-25T00:00:00Z",
          createdAt: "2026-08-25T00:10:00Z",
        },
      ],
    },
    collectionAttempts: [
      {
        attemptId: "attempt-24",
        hubId: hub.id,
        trigger: "manual",
        state: "succeeded",
        startedAt: "2026-08-26T00:04:59Z",
        completedAt: "2026-08-26T00:05:00Z",
        analyticsIntervalSeconds: 300,
        healthHttpStatus: 200,
        statsHttpStatus: 200,
        apiContract: hub.apiContract,
        healthSnapshotId: "health-snapshot-24",
        statsSnapshotId: "stats-snapshot-24",
        failureCode: "",
        failureDetail: "",
        normalizationErrorPath: "",
      },
      {
        attemptId: "attempt-23",
        hubId: hub.id,
        trigger: "scheduled",
        state: "failed",
        startedAt: "2026-08-25T23:59:59Z",
        completedAt: "2026-08-26T00:00:00Z",
        analyticsIntervalSeconds: 300,
        healthHttpStatus: 200,
        statsHttpStatus: 503,
        apiContract: hub.apiContract,
        healthSnapshotId: "health-snapshot-23",
        statsSnapshotId: "",
        failureCode: "stats_http_error",
        failureDetail: "stats API が HTTP 503 を返しました。",
        normalizationErrorPath: "",
      },
      {
        attemptId: "attempt-01",
        hubId: hub.id,
        trigger: "scheduled",
        state: "succeeded",
        startedAt: "2026-08-25T00:04:59Z",
        completedAt: "2026-08-25T00:05:00Z",
        analyticsIntervalSeconds: 300,
        healthHttpStatus: 200,
        statsHttpStatus: 200,
        apiContract: hub.apiContract,
        healthSnapshotId: "health-snapshot-01",
        statsSnapshotId: "stats-snapshot-01",
        failureCode: "",
        failureDetail: "",
        normalizationErrorPath: "",
      },
    ],
    rawSnapshots: [
      {
        snapshotId: "stats-snapshot-24",
        attemptId: "attempt-24",
        hubId: hub.id,
        responseKind: "stats",
        receivedStartedAt: "2026-08-26T00:04:59Z",
        receivedCompletedAt: "2026-08-26T00:05:00Z",
        httpStatus: 200,
        apiContract: hub.apiContract,
        body: currentStatsBody,
      },
      {
        snapshotId: "stats-snapshot-01",
        attemptId: "attempt-01",
        hubId: hub.id,
        responseKind: "stats",
        receivedStartedAt: "2026-08-25T00:04:59Z",
        receivedCompletedAt: "2026-08-25T00:05:00Z",
        httpStatus: 200,
        apiContract: hub.apiContract,
        body: startStatsBody,
      },
    ],
    costObservations: [
      {
        observationId: "cost-observation-codex-start",
        snapshotId: "stats-snapshot-01",
        hubId: hub.id,
        deviceId: "device-evaluation",
        rawServiceIdentifier: "codex",
        usageUpdatedAt: "2026-08-25T00:05:00Z",
        costUsdText: "0.000",
        syncUploadIntervalMs: 300000,
        analyticsIntervalSeconds: 300,
        sourceTimezone: "Asia/Tokyo",
        sourceLocalDate: "2026-08-25",
        normalizationGeneration: 1,
        normalizationRuleVersion: "api-stats-v1",
        normalizationLogicVersion: "t012-normalize-v1",
        jsonPath: "$.devices[0].usage.providers[0]",
        dedupeState: "canonical",
        dedupeKey: "evaluation-cost-codex-start",
        valueFingerprint: "0.000",
      },
      {
        observationId: "cost-observation-codex",
        snapshotId: "stats-snapshot-24",
        hubId: hub.id,
        deviceId: "device-evaluation",
        rawServiceIdentifier: "codex",
        usageUpdatedAt: "2026-08-26T00:05:00Z",
        costUsdText: "31.365",
        syncUploadIntervalMs: 300000,
        analyticsIntervalSeconds: 300,
        sourceTimezone: "Asia/Tokyo",
        sourceLocalDate: "2026-08-26",
        normalizationGeneration: 1,
        normalizationRuleVersion: "api-stats-v1",
        normalizationLogicVersion: "t012-normalize-v1",
        jsonPath: "$.devices[0].usage.providers[0]",
        dedupeState: "canonical",
        dedupeKey: "evaluation-cost-codex",
        valueFingerprint: "31.365",
      },
    ],
    limitObservations: [
      startLimitObservation,
      limitObservation,
      unassignedLimitObservation,
    ],
  });
}
