import {
  createFakeBackend,
  emptyDataManagementState,
  emptyOverviewSnapshot,
  type AuditRecord,
  type CatalogSnapshot,
  type DataManagementStateSnapshot,
  type HubSnapshot,
  type LimitObservationSnapshot,
  type LimitSeriesSnapshot,
  type OverviewSnapshot,
  type ReviewItemSnapshot,
} from "./backend";
import type { StatusPresentationSnapshot } from "../../bindings/token-monitor-analytics/internal/desktop/models.js";

const now = "2026-08-26T00:10:00Z";

function status(
  code: string,
  label: string,
  intent = "informative",
  icon = "info",
): StatusPresentationSnapshot {
  return {
    code,
    label,
    intent,
    icon,
    description: `${label}です。`,
    nextAction: "",
    nextRoute: "",
  };
}

const hub: HubSnapshot = {
  id: "hub-evaluation",
  displayName: "評価 Hub（192.168.0.16）",
  url: "http://192.168.0.16:17321",
  enabled: true,
  collectionEnabled: true,
  collectionIntervalSeconds: 300,
  apiContract: "schema=1; runtime=node-hub; usageUpdatedAt=false",
  credentialState: "registered",
  credentialReady: true,
  connectionState: "connected",
  connectionCheckedAt: "2026-08-26T00:05:00Z",
  connectionFailureNote: "",
};

const overview: OverviewSnapshot = {
  ...emptyOverviewSnapshot,
  generatedAt: now,
  timezoneConfirmed: true,
  checklist: [
    {
      step: 1,
      title: "表示タイムゾーンを確認",
      status: status("complete", "完了", "success", "checkmark"),
      route: "/settings",
      actionable: false,
    },
    {
      step: 2,
      title: "Hub と資格情報を登録",
      status: status("complete", "完了", "success", "checkmark"),
      route: "/hubs",
      actionable: false,
    },
  ],
  hubs: {
    ...emptyOverviewSnapshot.hubs,
    totalCount: 1,
    enabledCount: 1,
    scheduledCount: 1,
    credentialReadyCount: 1,
    lastSuccessAt: "2026-08-26T00:05:00Z",
    connectionStates: [
      {
        status: status("connected", "接続済み", "success", "checkmark"),
        count: 1,
      },
    ],
    currentCollectionStates: [
      { status: status("collection_idle", "待機中"), count: 1 },
    ],
    lastCollectionStates: [
      {
        status: status(
          "collection_succeeded",
          "取得成功",
          "success",
          "checkmark",
        ),
        count: 1,
      },
    ],
    items: [
      {
        id: hub.id,
        displayName: hub.displayName,
        enabled: true,
        collectionEnabled: true,
        connection: status("connected", "接続済み", "success", "checkmark"),
        currentCollection: status("collection_idle", "待機中"),
        lastCollection: status(
          "collection_succeeded",
          "取得成功",
          "success",
          "checkmark",
        ),
        lastCollectionAt: "2026-08-26T00:05:00Z",
        lastSuccessAt: "2026-08-26T00:05:00Z",
        lastFailureAt: "",
        lastSkippedAt: "",
      },
    ],
  },
  review: {
    ...emptyOverviewSnapshot.review,
    actionItems: {
      ...emptyOverviewSnapshot.review.actionItems,
      count: 2,
    },
    warnings: { ...emptyOverviewSnapshot.review.warnings, count: 1 },
    actionKinds: [
      { code: "identification_candidate", label: "サービス同定候補", count: 2 },
    ],
    warningKinds: [
      { code: "cost_timestamp_missing", label: "利用額観測時刻なし", count: 1 },
    ],
  },
  estimation: {
    states: [
      {
        status: status("provisional", "暫定推定", "informative", "info"),
        count: 1,
      },
    ],
  },
  capacity: {
    databaseSizeBytes: 12_582_912,
    rawSnapshotCount: 24,
    oldestSnapshotAt: "2026-08-25T00:00:00Z",
    latestSnapshotAt: "2026-08-26T00:05:00Z",
  },
  recentLimits: [
    {
      logicalAccountId: "account-codex",
      limitDefinitionId: "limit-weekly",
      serviceName: "Codex",
      accountName: "個人アカウント",
      limitName: "週次利用枠",
      cycleType: "weekly",
      remainingPercent: 74.5,
      remainingLabel: "74.5%",
      remainingDetailLabel: "74.50%",
      remaining: status("remaining_high", "残量良好", "success", "checkmark"),
      resetAt: "2026-09-01T00:00:00Z",
      reset: status("reset_scheduled", "リセット予定"),
      lastIncrease: { occurredAt: "2026-08-26T00:00:00Z", ageLabel: "10分前" },
      freshness: {
        status: status("freshness_current", "最新", "success", "checkmark"),
        reason: "最新の取得に含まれています。",
        observationAt: "2026-08-26T00:05:00Z",
        ageLabel: "5分前",
      },
      privacyMasked: false,
      accessibleLabel: "Codex、個人アカウント、残り 74.5%",
      tooltip: "週次利用枠、残り 74.5%",
    },
    {
      logicalAccountId: "account-claude",
      limitDefinitionId: "limit-session",
      serviceName: "Claude",
      accountName: "作業アカウント",
      limitName: "5時間利用枠",
      cycleType: "session",
      remainingPercent: 42,
      remainingLabel: "42.0%",
      remainingDetailLabel: "42.00%",
      remaining: status("remaining_medium", "残量注意", "warning", "warning"),
      resetAt: "2026-08-26T05:00:00Z",
      reset: status("reset_scheduled", "リセット予定"),
      lastIncrease: { occurredAt: "2026-08-26T00:03:00Z", ageLabel: "7分前" },
      freshness: {
        status: status("freshness_current", "最新", "success", "checkmark"),
        reason: "最新の取得に含まれています。",
        observationAt: "2026-08-26T00:05:00Z",
        ageLabel: "5分前",
      },
      privacyMasked: false,
      accessibleLabel: "Claude、作業アカウント、残り 42.0%",
      tooltip: "5時間利用枠、残り 42.0%",
    },
  ],
};

const limitSeries: LimitSeriesSnapshot = {
  id: "series-codex-weekly",
  serviceId: "service-codex",
  serviceName: "Codex",
  logicalAccountId: "account-codex",
  logicalAccountName: "個人アカウント",
  limitDefinitionId: "limit-weekly",
  limitDefinitionName: "週次利用枠",
  cycleType: "weekly",
  usageLimitSourceId: "source-weekly",
  associationId: "association-weekly",
  normalizedKind: "weekly",
  normalizedMetric: "percent",
  planHistoryId: "plan-history-plus",
  planVersionId: "plan-plus-2026",
  planVersionName: "Plus 2026",
  planLimitRuleId: "rule-plus-weekly",
  planLimit: 1000,
  planLimitLabel: "1,000.00",
  multiplier: null,
  usedPercent: 25.5,
  usedPercentLabel: "25.5",
  usedPercentDetailLabel: "25.50",
  remainingPercent: 74.5,
  remainingLabel: "74.5%",
  remainingDetailLabel: "74.50%",
  resetAt: "2026-09-01T00:00:00Z",
  latestObservationAt: "2026-08-26T00:05:00Z",
  seriesState: "normal",
  state: status("provisional", "暫定推定", "informative", "info"),
  stateReasonCode: "exactly_identified",
  stateReason: "利用枠観測から暫定値を算出しました。",
  currentInterval: null,
  result: null,
  latestValidReference: null,
  estimatedLimit: 123,
  estimatedLimitLabel: "123.00 USD相当",
};

const reviewItem: ReviewItemSnapshot = {
  id: "review-cost-timestamp",
  kind: "identification_candidate",
  state: "unconfirmed",
  impact: "current_calculation_impact",
  hubId: hub.id,
  sourceId: "source-codex",
  targetId: "candidate-codex",
  target: "Codex / Plus",
  rawLimitServiceIdentifier: "codex",
  rawReportedPlanName: "Plus",
  accountKey: "account-key",
  accountDisplayName: "個人アカウント",
  workspaceName: "Personal",
  deviceName: "評価端末",
  firstObservedAt: "2026-08-25T00:00:00Z",
  lastObservedAt: "2026-08-26T00:05:00Z",
  targetPeriodStart: "2026-08-25T00:00:00Z",
  targetPeriodEnd: "2026-09-01T00:00:00Z",
  count: 12,
  evidenceIds: ["observation-weekly"],
  estimationExclusionReason: "利用額観測時刻がないため利用額推定から除外",
  currentAssociation: null,
};

const audit: AuditRecord = {
  sequence: 12,
  auditId: "audit-hub-connected",
  occurredAt: "2026-08-26T00:05:00Z",
  actor: "user",
  action: "hub_connection_succeeded",
  entityType: "hub",
  entityId: hub.id,
  beforeJson: '{"connectionState":"not_checked"}',
  afterJson: '{"connectionState":"connected","credential":"[非表示]"}',
};

const dataManagementState: DataManagementStateSnapshot = {
  ...emptyDataManagementState,
  capacity: {
    status: "success",
    capacity: {
      databaseSizeBytes: 12_582_912,
      rawSnapshotCount: 24,
      oldestCompletedAt: "2026-08-25T00:00:00Z",
      latestCompletedAt: "2026-08-26T00:05:00Z",
      rawJsonBytes: 8_388_608,
    },
    error: null,
  },
};

const catalog: Partial<CatalogSnapshot> = {
  services: [
    {
      id: "service-codex",
      provider: "OpenAI",
      name: "Codex",
      officialKey: "openai.codex",
      archivedAt: "",
      createdAt: "2026-08-25T00:00:00Z",
      updatedAt: "2026-08-26T00:05:00Z",
    },
  ],
  limitDefinitions: [
    {
      id: "limit-weekly",
      serviceId: "service-codex",
      cycleType: "weekly",
      meaning: "週次利用枠",
      unit: "%",
      billingConfirmation: "not_applicable",
      archivedAt: "",
      createdAt: "2026-08-25T00:00:00Z",
      updatedAt: "2026-08-26T00:05:00Z",
    },
  ],
  plans: [
    {
      id: "plan-plus",
      serviceId: "service-codex",
      name: "Plus",
      isBaseline: true,
      archivedAt: "",
      createdAt: "2026-08-25T00:00:00Z",
      updatedAt: "2026-08-26T00:05:00Z",
    },
  ],
};

const limitObservation: LimitObservationSnapshot = {
  observationId: "observation-weekly",
  snapshotId: "stats-snapshot-24",
  hubId: hub.id,
  deviceId: "device-evaluation",
  rawServiceIdentifier: "codex",
  accountKey: "account-key",
  providerUpdatedAt: "2026-08-26T00:05:00Z",
  windowKey: "weekly-percent",
  normalizedKind: "weekly",
  normalizedMetric: "percent",
  normalizedLabel: "Weekly",
  planLabel: "Plus",
  usedPercent: 25.5,
  remainingPercent: 74.5,
  resetsAt: "2026-09-01T00:00:00Z",
  syncUploadIntervalMs: 300000,
  limitsRefreshMs: 300000,
  analyticsIntervalSeconds: 300,
  sourceTimezone: "Asia/Tokyo",
  sourceLocalDate: "2026-08-26",
  normalizationGeneration: 1,
  normalizationRuleVersion: "api-stats-v1",
  normalizationLogicVersion: "t012-normalize-v1",
  jsonPath: "$.devices[0].limits.providers[0].windows[0]",
  dedupeState: "canonical",
  dedupeKey: "evaluation-weekly",
  valueFingerprint: "25.5",
  windowKeyConflict: false,
};

export function createShowcaseBackend() {
  return createFakeBackend({
    canOpenMain: true,
    settings: { displayTimeZone: "Asia/Tokyo" },
    overview,
    hubs: [hub],
    limitSeries: [limitSeries],
    reviewItems: [reviewItem],
    audits: [audit],
    dataManagementState,
    catalog,
    accounts: {
      logicalAccounts: [
        {
          id: "account-codex",
          serviceId: "service-codex",
          displayName: "個人アカウント",
          archivedAt: "",
          createdAt: "2026-08-25T00:00:00Z",
          updatedAt: "2026-08-26T00:05:00Z",
        },
      ],
    },
    collectionAttempts: [
      {
        attemptId: "attempt-24",
        hubId: hub.id,
        trigger: "manual",
        state: "succeeded",
        startedAt: "2026-08-26T00:04:59Z",
        completedAt: "2026-08-26T00:05:00Z",
        analyticsIntervalSeconds: 300,
        healthHttpStatus: 200,
        statsHttpStatus: 200,
        apiContract: hub.apiContract,
        healthSnapshotId: "health-snapshot-24",
        statsSnapshotId: "stats-snapshot-24",
        failureCode: "",
        failureDetail: "",
        normalizationErrorPath: "",
      },
    ],
    rawSnapshots: [
      {
        snapshotId: "stats-snapshot-24",
        attemptId: "attempt-24",
        hubId: hub.id,
        responseKind: "stats",
        receivedStartedAt: "2026-08-26T00:04:59Z",
        receivedCompletedAt: "2026-08-26T00:05:00Z",
        httpStatus: 200,
        apiContract: hub.apiContract,
        body: '{"devices":[{"deviceId":"device-evaluation","limits":{"providers":12},"secret":"[MASKED]"}]}',
      },
    ],
    limitObservations: [limitObservation],
  });
}
